{BAT
bna:Celera Assembler
crt:1330637220
acc:1132501791962
com:
scratch assembly
.
}
{ADT
{ADL
who:dkatzel
ctm:1330637249
vsn:1.00
com:
pullfrag -D giv -c 15048
.
}
.
}
{DST
act:A
acc:1100010858474
mea:550.00
std:16.67
}
{DST
act:A
acc:1100010858465
mea:418.00
std:16.67
}
{DST
act:A
acc:1100010858483
mea:563.00
std:16.67
}
{DST
act:A
acc:1132501791961
mea:10.00
std:1.67
}
{DST
act:A
acc:1100010858471
mea:514.00
std:16.67
}
{DST
act:A
acc:1100010858468
mea:560.00
std:16.67
}
{DST
act:A
acc:1100010858480
mea:765.00
std:16.67
}
{DST
act:A
acc:1100010858477
mea:447.00
std:16.67
}
{DST
act:A
acc:1099820534362
mea:1027.00
std:16.67
}
{FRG
act:A
acc:1099820573469
typ:R
src:
IWKNA07T07A12MP1027R
.
etm:1157567520
seq:
gtccatctcttactccagctctatgttgacaaatgaccatcgtcaacatccacagcactctgctgttcct
gctgatattcttccctcatagactcaggcactccttccgtagaaggccctcttttcaaaccgtatttaag
gcgacgataaatgcatttgaagaaaagacgatcaagaatccacaatatcaagtgcaagatcccaatgata
cttgcggcaataacgagaggatcacttgaatcgctgcatctgcactcccatccgtttctggtaggcctgc
aaattttcaagaagatcatcttttagaccagcactggagctaggatgagtcccaatggtcctcattgcct
gcaccatctgtctggcctgactagcaacctccatagcctctgctgcctgctcacttgaccctgccatttg
ctccatggccttagccgtagtactggccaataccattctgttctcgtgtctgattaggggattggttgtt
gtcaccatttgtctgtgagaccgatgctgggaatcagcaatctgctcacacgtggcgcacactagaccaa
atgccacttcagtggtcacagtccccatcctgttgtatatgaggcccatgcaactggcaagtgcaccggt
tgaataactgagtgccacttcttttgccccatgaaatgttatttcccttttaagctttctgtacagtttg
accgctctgtccatgttgtttggatccccattcccattaagggcattctggacaaagcgtctacgctgca
gtcctcgctcactgggcacgggtgagcgtgaacacaaatcctaaaatccccttagtcagaggtgacagga
ttggtcttgtctttagccattccatgagtgcctcaagatcggtgtttttccctgcaaacacatcttcaat
tctctgcgcgatctcggctttgagggggcctgacgggacgatagagagaacgtacgtttcgacctcggtt
agaagactcatctttaaatatctac
.
qlt:
666666666877@=7X7C>A=>CCCHE@>::CCEEEBGCCCDDEEEDGGGKIMHOQRPMXXXTTaXK<<9
99999=99=@TPTVVRRMLJGLLJSMSMSSRSM]XVXPBA9999?CRRSRTVVJJHOQPSWXXPR\VVVV
XRIGG;;BFBHJXTXPVaaaXII]]MMIKDDEIXLDGLLVVMMLLXPPXPXXXPWWLJJLLV\XXLPPXP
XXaaXV__T]RPWPKKaLGHGGEKGLLMTTVXXXXTXRXTXXXLLPMOMSSMPLLTaaaXRXRRPT]TXP
X]LX]RVVMPIKICBPNSTPaVPMWDCMM]LLWXRXXXPPPaLHJJHMXSX]]]XLa]aT]]_]]PTWWL
LXXX_XXPRRaaRa]]aXPPPXTPPTX\XXXXXXLLPaLLPPXXX]XPRXPX\XXXX_\]TaPXPRXWX_
VRMMLLO]a]]aaRaWLLXLLXLLWX_____XXXTXVaaaaVXTXXRaaaLLMLRVXXNLRSS\]aaa]_
TTXXXVX__aaaaaaTXGDDNHRaPaaa]]XXXT]XaPXXXXXaXXP]W_TTaTa]XTLLLXKWCCMM]X
VTTX\\XX]WPMDJPRS]]TWPTX]__XWaaaaXXX]PPLLPXX]]]VRPP]V__a]X_XTRXTV__XaK
K=KGHRITTXLPLTTTTXTTTPT\XX]T]PPPGLTWPPTX_TTTTPP]KHJLOJLTTT_TTXT]PPT]LL
WWTV_XWXRX]XRR\V__TR]RGR\___XXXX\\VVPMOQSQQISVVWWJINNX\TTT_]TKKIHBHNNG
DDFFHKHLOOCHDDTNHHCCC@@D=PHRREEMGJIXCPXTXXWMGLHCOWHHHWHHLCCQGLCFCCGJRK
GH\XXRM\X\X__KKJJKMOQRISSS\VR\VVSRVV\XVS\]]X]_H?;;?=?CGILNQQQSR?><>C@N
PP_]__]XJJMRXEB77BBHHIK<;99B@B=BB;:977>AKJKEFQNONMGGKGFGGNE<79@BA@@>?;
9==999<FHMQMKGCA::BB;99?9
.
clr:9,996
}
{FRG
act:A
acc:1099820534363
typ:R
src:
IWKNA07T07A12MP1F
.
etm:1157567520
seq:
cacgaatgattttagatgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggcc
ccctcaaagccgagatcgcgcagagaattgaagatgtgtttgcagggaaaaacaccgatcttgaggcact
catggaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcacg
ctcaccgtgcccagtgagcgaggactgcagcgtagacgctttgtccagaatgcccttaatgggaatgggg
atccaaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatggggc
aaaagaagtggcactcagttattcaaccggtgcacttgccagttgcatgggcctcatatacaacaggatg
gggactgtgaccactgaagtggcatttggtctagtgtgcgccacgtgtgagcagattgctgattcccagc
atcggtctcacagacaaatggtgacaacaaccaatcccctaatcagacacgagaacagaatggtattggc
cagtactacggctaaggccatggagcaaatggcagggtcaagtgagcaggcagcagaggctatggaggtt
gctagtcaggccagacagatggtgcaggcaatgaggaccattgggactcatcctagctccagtgctggtc
taaaagatgatcttcttgaaaatttgcaggcctaccagaaacggatgggagtgcagatgcagcgattcaa
gtgatcctctcgttattgccgcacgtatcattgggatcttgcacttgatattgtggattcttgatcgtct
tttcttcaaatgcatttatcgtcgccttaaatacggtttgaaaagagggccttctacggaaggagtgcct
gagtctatgagggaagaatatcggcaggaacagcagagtgctgtggatgttgacgatggtcattttgtca
acatagagctggagtaaaaactaccttgttcttgtgcatttttttttttttctggtgaggaggga
.
qlt:
686686999866<88;:@BEEOQCCGMGJJJIQQRKMLKKKQSSRV]]V_aSRMQOMVSVTVMMOHHITT
_TOHDGJJPWaPRSRRRS\]\XXXRR\\\RTJJJMMI]\\MRSRLNSVVRVV\SQONNHKGWKX\V\\\\
\RSS]SV\\V\RXTXPTXX__MV\\\VaaaY\VKKFCPIPQQQRRSaOMV\\\_VVRV\\VY__VVVV\V
___T\VVV\VVXVRSVV\V__\\\\VVaVaPW]LLLLLLaa_Y\\VVVV_____Y_TXWSP]W_____\\
V\V\]_]]__]VMNNNQKRTX_VV_____V_YVX_TY_______]V\RX\V__]_]__V_VWXLLLWXY_
_]]XaXT____V__XWXRRWXV______aa__]____V\\\RRX]XX__]]_YWWXLLOORSMMT_V___
___\VRMQQSOQVV_aaa_________aa___XTRV\_Y_____Y_a_]_V]XPPWXX]X_____V__TY
_____a_V_]\]PPIIXXa_a_VVXX______Y__aa]]_Y_PPJJPPWXXXSPTWVPXXPPRS\\\\__
__Y__]__aa__V_________a_]X_XXV]____a_______YTTT__THHa]aKIXXTTTT__VVVVa
V]_VT__THT_TTRRaRPT]T_Y_YTYTYT____TYYYYTYYaTYT_TTTVTTTPPPWTLIIaHTTT_TT
VVTTTHTTTTTTTV]VTTTY]]YTYT_TTTTT]VTMPHAHGHEEEFNRT_T_T_TVT]\XVV\SV\K\VX
XT]TT___\_aY\VV\V\TY><967=@]__V_]\\\]______YV\S\\]__]________Y__Y_____
VVV\VV\X\\\VRSSSS\_\_YVXXXXX\\_XXSSV\T_V\\VR]@@99?@MXRQ@<79><66<?MRRSN
NJRV\SIRRQRA@@99B99BFRMB=77=>99A@RIRTTTNEE>BE::<<DD<?;:<::?<@N_NDA?A<<
HCFFDHQA=8:<:E;<@99989=A><<????9999:988A:9>:A:>?<:999:9?999979:88
.
clr:14,995
}
{FRG
act:A
acc:1099820574236
typ:R
src:
IWKNA07T07E12MP1027R
.
etm:1140209760
seq:
gcgcggttttttctcagctctatgttgacaaatgaccatcgtcaacatccacagcactctgctgttcctc
cctatattcttccctcatagactcaggcactccttccgtaaaaggccctcttttcaaaccgtatttaagg
cgacaataaatgcatttgaagaaaagacgatcaagaatccacaatatcaagtgcaagatcccaatgatac
ttgcggcaataacgagaggatcacttgaatcgctgcatctgcactcccatccgtttctggtaggcctgca
aattttcaagaagatcatcttttagaccagcactggagctaggatgagtcccaatggtcctcattgcctg
caccatctgtctggcctgactagcaacctccatagcctctgctgcctgctcacttgaccctgccatttgc
tccatggccttagccgtagtactggccaataccattctgttctcgtgtctgattaggggattggttgttg
tcaccatttgtctgtgagaccgatgctgggaatcagcaatctgctcacacgtggcgcacactagaccaaa
tgccacttcagtggtcacagtccccatcctgttgtatatgaggcccatgcaactggcaagtgcaccggtt
gaataactgagtgccacttcttttgccccatgaaatgttatttcccttttaagctttctgtacagtttga
ccgctctgtccatgttgtttggatccccattcccattaagggcattctggacaaagcgtctacgctgcag
tcctcgctcactgggcacggtgagcgtgaacacaaatcctaaaatccccttagtcagaggtgacaggatt
ggtcttgtctttagccattccatgagtgcctcaagatcggtgtttttccctgcaaacacatctcaattct
ctgcgcgatctcggctttgaggggcctgacgggacgatagagagaacgtacgtttcgacctcggttagaa
gactcatctttaaatatctacctgc
.
qlt:
:666678>>DB97<8A?@==>@@CGC>@8:>@BDD?<==<==DBEAEEEEEGGKMHHBEKPMLPTTA@77
9999:99?EXXXVSLLGGBCICEDFDDPLLPXaaaKG>=9<7<9<>IJLPaTMMKKKGLXLLPMSMQLMM
MDC::<<@@@BLLLGaPPKLCCKGFFFE@D=>GILLPHMGC:99>;9CCGLLLPXXLLPPXRXXEGKGGJ
LXPXXPRXXIIWK>@KGDFIFDFIGWXTTTRRaRRPXXXRXPGLXPTPRPPLLLXWVXPPPLLXaaXPXP
PIPTMVSNLDGKDD]MPXXR\TMG>>GGJJMXPLMMMMMSNKGELJJXPRMVMMLPTTPT]XXXRW]TLL
XPXXXXPaaaaPXXWTRPPPXTLLXXPTXPPPPLLLPKKKaXTTWXXPTPXPRXWXP\VXRXXXLLXXXX
XXPPP]]aVPPXLKWIGMIIWMLPXX_]]PPXV_TXaaaaaPPPXXTWXGLXXPXXXNHMSMSaaa_aa]
TXXRVV___TaaaaTKGEEWKPPWPRaaXXRVXXPXPWPXXXPXXXXTWTRaa]aMMLGGXKaKCMK]]T
TXTVXXXWXPLIXWV_]XXXLaXV\XPXaLLaWXX]TXXDDXXX\__TTXTXXaaXX_]XP]X_VV]]HD
DTTV_\XXXaaLXP\\PX]XXVX]RXT]XWXGLXTPPHVM\VVa]aR\RPWXXGXWWXTRRRRRSV]TLT
XVTPXWPLLOMHJ\TY_YXWLMSRVV]TT\TPXXTPHNNONQNMHMMTHGJNHSPPVHPTIC::9@AD@=
9@DTLHPTPTLHMHIIMOKIGJCRHTTFCEHIH]HTXHG:8@@ECTHHCCHCAECHCRKCCCCECCTCPC
C==KHHHMKTNCEBDCCDICECCHCHHHCJHCGQCGDABHNMMRNG>;A@CCCLGLHHEE><<<=<KKKH
C=;8:<;@]]JI89ABA;:977<CFC=>=99<:;<99;;;9:B99A@FBC=AHHDA<<BBB99==87996
76:=8999@AJHH:89;;::76897
.
clr:43,966
}
{FRG
act:A
acc:1099820534711
typ:R
src:
IWKNA07T07E12MP1F
.
etm:1140209760
seq:
aaggttgaatttaagatgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggcc
ccctcaaagccgagatcgcgcagagaattgaagatgtgtttgcagggaaaaacaccgatcttgaggcact
catggaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcacg
ctcaccgtgcccagtgagcgaggactgcagcgtagacgctttgtccagaatgcccttaatgggaatgggg
atccaaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatggggc
aaaagaagtggcactcagttattcaaccggtgcacttgccagttgcatgggcctcatatacaacaggatg
gggactgtgaccactgaagtggcatttggtctagtgtgcgccacgtgtgagcagattgctgattcccagc
atcggtctcacagacaaatggtgacaacaaccaatcccctaatcagacacgagaacagaatggtattggc
cagtactacggctaaggccatggagcaaatggcagggtcaagtgagcaggcagcagaggctatggaggtt
gctagtcaggccagacagatggtgcaggcaatgaggaccattgggactcatcctagctccagtgctggtc
taaaagatgatcttcttgaaaatttgcaggcctaccagaaacggatgggagtgcagatgcagcgattcac
gtgatcctctcgttattgccgcagtatcattgggatcttgcacttgatattgtggattcttgatcgtctt
ttcttcaaatgcatttatcgtcgccttaaatacggtttgaaaagagggccttctacgggaaggagtgcct
gagtctatgagggaagaatatcggcaggaacagcagagtgctgtggatgttgacgatggtcattttgtca
acatagagctggagtaaaaactaccttgttttcgtgc
.
qlt:
9899999777<<=;9<<88;<FFCCCEFF??CFCFFCCJHLJLLJHNJMROFFEDDFNLSXTEFECDCCH
MNFB><AAIaLLA@FFEEKHKGLLJJSOMMPJMJNLMXXRLJJLIQSS\QTPPGEGHHKKHJDLXMRVMM
MLLLWWPPWPLKKXJLMMLJLJKLRRVX\aP\VVRVMaHJJJHLGLLKKVVVMILGKHKSMTTRSRR\NN
VVVRXVV_a\VNKKKMMV\\\QVVVVMPPKLMKDEAA>=a]_TVRMRSRPXR]]_VVWPLLXKVRVV\\V
\V\SSRRRX]]VMKHKFDHXW_]]PXTX]V_TTXTT__VTR]]__]WLPWXV\VVVSXVX_WXLGGTXX]
VXXPLMSMRVV]XPTXLLHKKRRRTXX]]a_X]XXXVXTXXXPXTTVRTXaaXXXPII]]LLLPMQNQQR
OQQQPQPQNNKGNMRVV\S_WXPX\]_aa_V\XVXa]aa_______T]XRXXXLLLLP]LSS\VV]V__\
VTTaTaRRT]]]MMKAKWW___\V\RXVV_______a_Y__TPPJJLPWPLLLLPSWPXLLLXX_____T
______]Va]aaa]XVX\\_]VV\RR]]X]aaaaaa______aaaTaaTXX\WWMAAWW___a_______
VXXWXXaaa_V]RRPPPPWTXVTTTTTTTTVTTVHHTTTTTTaTYT_\]]TPHaaLLTHGGCaHHTT_HT
TH]]HCMKHCCCKTTV]VTSSSKK\THTHTTTTTHEGJEECHGCEEMWTTH_T\VMSVMRVV\V\]D>76
<EFVT__\]___________CBBBB?_____aX__Y____________Y__V\RIOOMOIP_\TPR]\_\
VOORRRR\V____]_Y____TTGEEMMPV]]VX]\RMKKHFF@?=<<ADECEJJVNCG::;77?@LTPPW
TMHMMRHKBBGB>>99?99??<99>99@@NIHHE==CGHSGH<:<BCCLF?;CA==::A<GGFHHOKH?@
JLBB<<?BHMJJNLP??99<==@CA?HBBB99999::
.
clr:9,995
}
{FRG
act:A
acc:1099820574024
typ:R
src:
IWKNA07T07H08MP1027R
.
etm:1157567520
seq:
gtcgatgtttttactccagctctatgttgacaaaatgaccatcgtcaacatccacagcactctgctgttc
taaagttattcttccctcatagactcaggcactccttccgtataaggccctcttttcaaaccgtatttaa
ggcgacgataaatgcatttgaagaaaagacgatcaagaatccacaatatcaagtgcaagatcccaatgat
acttgcggcaataacgagaggatcacttgaatcgctgcatctgcactcccatccgtttctggtaggcctg
caaattttcaagaagatcatcttttagaccagcactggagctaggatgagtcccaatggtcctcattgcc
tgcaccatctgtctggcctgactagcaacctccatagcctctgctgcctgctcacttgaccctgccattt
gctccatggccttagccgtagtactggccaataccattctgttctcgtgtctgattaggggattggttgt
tgtcaccatttgtctgtgagaccgatgctgggaatcagcaatctgctcacacgtggcgcacactagacca
aatgccacttcagtggtcacagtccccatcctgttgtatatgaggcccatgcaactggcaagtgcaccgg
ttgaataactgagtgccacttcttttgccccatgaaatgttatttcccttttaagctttctgtacagttt
gaccgctctgtccatgttgtttggatccccattcccattaagggcattctggacaaagcgtctacgctgc
agtcctcgctcactgggcacggtgagcgtgaacacaaatcctaaaatccccttagtcagaggtgacagga
ttggtcttgtctttagccattccatgagtgcctcaagatcggtgtttttccctgcaaacacatcttcaat
tctctgcgcgatctcggctttgagggggcctgacgggacgatagagagaacgtacgtttcgacctcggtt
agaaaactcatctttaaatatctactgctccatcg
.
qlt:
76666678>78<X9A7X9D>AAICCBH<;:9=@<DDD@><@=@><=99<ABEAGMHRQRRMMXRTPP=>7
9678799978;GXX]MMLGKDGLKMSKMSRMRSR_VWTD=96797:>9=<>GMTMQPQOPOXLLPMRVVV
VXRHILDDPXXWPPXPXVXaaXLI]]RKHKGFKLLJJLXLV\VHHDCLKXPXTPXWXTLLTM\VKMJLXP
RXTVaXVV_X]RPWPEDaLMMSSSRPPXX_TXRRXVTRRXTXXLLXPMSSRRVaaX]VXRPXPRRR\XXT
XT]XX]R\VPNHLMDDPNSRTTXXNNEBKKLLLPNRSRSRPXWRRRMSSXPVVVOMLPaTa_]TPRXaaa
RRPRPVXRXaaaVXXXXXMRRMMMXX]]TVRRRSMLaa]TTXXWTTVVXRRRRMMV\__VVXXXTXXR]]
]aXRTXR]]V\\VVRXXXXXXPXWRR\V___V]XVXXVaaaaaaRaPaa]VXXXWXXXWNLRQKQ]X__a
a]XRXT_T__aVaaaaTXJGGNLRaTa_aT\RXWWXXaPTX_V_aXXRVXXXRXT]aXX]X_TNPBCNN_
]]aXXWX_VTaaaGLXXXTXXXXaWV\XR]aaPTa___V\SSSSTX___TT_XVSR\V\\]XRTXVX_aa
TTRHRR]\aaTaXLXW\VPXXa_TTTTTT_TTTLPTXPPTV_VV_____TTTT]XRT]T_HVOVVVV\\T
TVT_VVTPTTTTTPPXTY\XVTPPPTTT]TTTTPTTTTTMSSSSHR]TTPIIHLKSTPPTPTTTTTLTTT
TLGHPTTHRKMHJIRHIICGCECFHTTTTCCKKMOMCISGMSSKMVMMKTHHHOHEHTTPCCHCGIHLLH
HEGIIJMKS\XTTTHBB=@DDECMCMTWLKHCCCFMVHCIGSZZ]RKCJWaYHHHHMOPSO_SSGGHHIL
ILSXZSSRRS\__\MMIKJOXPUG@EAGGGEGEEINSSOPNNPPXKGIIPOOQNAFKNNEANMKMMKIGI
HCC::<<<=C@>EGGDHNKIKMS]IBAA=999779
.
clr:10,1001
}
{FRG
act:A
acc:1099820534733
typ:R
src:
IWKNA07T07H08MP1F
.
etm:1140209760
seq:
aacgaatgatttaagatgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggcc
ccctcaaagccgagatcgcgcagagaattgaagatgtgtttgcagggaaaaacaccgatcttgaggcact
catggaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcacg
ctcaccgtgcccagtgagcgaggactgcagcgtagacgctttgtccagaatgcccttaatgggaatgggg
atccaaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatggggc
aaaagaagtggcactcagttattcaaccggtgcacttgccagttgcatgggcctcatatacaacaggatg
gggactgtgaccactgaagtggcatttggtctagtgtgcgccacgtgtgagcagattgctgattcccagc
atcggtctcacagacaaatggtgacaacaaccaatcccctaatcagacacgagaacagaatggtattggc
cagtactacggctaaggccatggagcaaatggcagggtcaagtgagcaggcagcagaggctatggaggtt
gctagtcaggccagacagatggtgcaggcaatgaggaccattgggactcatcctagctccagtgctggtc
taaaagatgatcttcttgaaaatttgcaggcctaccagaaacggatgggagtgcagatgcagcgattcaa
gtgatcctctcgttattgccgcaagtatcattgggatcttgcacttgatattgtggattcttgatcgtct
tttcttcaaatgcatttatcgtcgccttaaatacggtttgaaaagagggccttctacggaaggagtgcct
gagtctatgagggaagaatatcggcaggaacagcagagtgctgtggatgttgacgatggtcattttgtca
acatagagctggagtaaaaactaccttgttctatgttagt
.
qlt:
66667778787;;=>>>>>CHX]CCCFEGHCOPIIGHGLLNQNRRV\]XTaVVVORR\VST\SROVRRXW
GK<:8799BDPPJJRRVV_]]XXXRR\\\VXJGGMLL\_XWPXPEDJMPQ_]ORQSV]]RaVVT_\VVVV
VSPQV\\VV__V]]]MVVVMRRV\VVVaaaV\VVRV_VRRRRQ\VVa\\\V\\_XVRV\\VY__V_V___
_\VRXTVY___XVXXXXVY__\VVV\]a]_T]\RRXXX_a_a]]\\MRR\V\\_Y_Y\VXP\V_____\\
V\VV]]]]_]_V]___V_T__Y___T_______T_____VY_Y__\]RRV\VV\V\S____Y_YY_a_Y_
__]___]____Y__VXXRRVXV_______a__V____VV\\\VX]V\___aa__]_T_]]_]]_a____Y
Y__Y___RVOVRVQQ]]V\T_______aa_V\XV_aaa_]____Y_a]]_V\\RRV]Ya______]V___
YVV]_V\V]T\VXXTX]_aa__TY___________aa______]WXRXXVXXLLWX__X\X__Y____]]
aaYTT_T_T_TT______________________________a_aaaaaa___XWXRXW__\]V_\\___
_VV\_____]aaXRX\\_____________Y__Y__]_____a_______Y_VWTPRRMVOV\]]T__Y_
_V_]VVVOVVVT_]]V__YVSSVXVTTTTRTTYVTTYYXTTVTPTPP\T_T_VY__Y_______T_____
____T_\\_\__\V\\\\Y_____\]VV\\\\_STS\]\______\\\VV\_Y_POOMOP\SV_TTY___
_Y__]\\X\XV\\_\\V\\Xa_XVXV\V\\]_____VX__YT_V\VVVJGHMMGONCCJQMMMVVTWPPT
TXPPMMNJDCHHIIGBB99BCK\QQAB?@:9DCMIMTVTKDBABB<<>BO\MQJNMM\\XSIISSSSOOP
PPVOPJCACFEFKF<B99;:ADCELH@BBBBB97C?9898
.
clr:9,995
}
{FRG
act:A
acc:1100010858466
typ:R
src:
IWKNA07T08G01MP1F
.
etm:1140209760
seq:
ggaagattttacgatgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggcccc
cctaaagccgagatcgcgcagagaattgaagatgtgtttgcagggaaaaacaccgatcttgaggcactca
tggaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcacgct
caccgtgcccagtgagcgaggactgcagcgtagaccctttgtccagaatgcccttaatgggaatggggat
ccaaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatggggcaa
aagaagtggcactcagttattcaaccggtgcacttgccagttgcatgggtctcataggtcatact
.
qlt:
776668:66>7:6<ABBCHKRHHIMSCHHICIINOIIMHGIGGHVR\RVVVNNQQSV]\_MMSMHGCC9:
99>9FGV__XMGGNNP_XXXGGFFJJGKPJGGHHQRRV\RJMJR]__\]]]\\YXaLKK]]__\\\VVVV
VV_________W]LMMMVRS\M\V\]a_V\V\VVWaPXSRMSRSPNKRRMKKNKFKMVVYXTRSRRRSXX
PXX\V]a___XXRVPTX__VV\\VVVXXRXWG@@>;9GF__VRRSSRX]_]aY_YWXRaWX_Y_Y_\\V\
\\____]]_TYY]WXXSXT__V______Y_VXTTXP]VY_Y______a_V\\]V\____XWLLLWX_V_]
aaaXWXRVVV_TXXGLLWX___YYV\]_]]VXRV\_\XXXX]]SPX]__V_NKLCCIHSNBD876
.
clr:6,385
}
{FRG
act:A
acc:1100010858901
typ:R
src:
IWKNA07T08G01MP418R
.
etm:1140209760
seq:
catcactgggcagtgcaccggttgataactgagtgccacttcttttgccccatgaaatgttatttccctt
ttaagctttctgtacagtttgaccgctctgtccatgttgtttggatccccattcccattaagggcattct
ggacaaagcgtctacgctgcagtcctcgctcactgggcacggtgagcgtgaacacaaatcctaaaatccc
cttagtcagaggtgacaggattggtcttgtctttagccattccatgagtgcctcaagatcggtgtttttc
cctgcaaacacatcttcaattctctgcgcgatctcggctttgagggggcctgacgggacgatagagagaa
cgtacgtttcgacctcggttagaaaactcatctttaaatatctacctgctttcgctactggccg
.
qlt:
6666:67<<=A>C>>>><<=JGIDFGGGGGGHEB@>?D?@QRRRKJKKDMEEEEQJIEEKKJ____THTF
DBFFMX__RIKLKKJHHI]QQQQ\V__V__PPNJJGT___VXMMVRS]R\VVVVV\VMVXTTVVVVVQSX
KKKONVOVSMNNHKHBCWWXPLLWWXaPXVVWXPPWRV\VVQRRRRSVX_V\\__]]VaWXLL]]]TTVV
_XPXLLMMCCNWTXPXXPXPVXXaVVV_TVPSNLSLL]XXVVVRMMLXLTX]XXKKDGWXTaaaaa]___
_]TXV]]VXXXRXWJHJNLMaaPTXVXPPPXWTVXT]TaaaPaaaTVXVVNQKNLSPXX>>>>=HHKLLX
WXXPXLLa]aLL]aaR]XGGXG?I<=HDPWXPPXXXWVRXWWaaLPa]a_WXRSPTXLLNLDD<
.
clr:5,391
}
{FRG
act:A
acc:1100010858902
typ:R
src:
IWKNA07T08G02MP564R
.
etm:1140209760
seq:
ctttctgcctgattaggggatggttgttgtcaccatttgtctgtgagaccgatgctgggaatcagcaatc
tgctcacacgtggcgcacactagaccaaatgccacttcagtggtcacagtccccatcctgttgtatatga
ggcccatgcaactggcaagtgcaccggttgaataactgagtgccacttcttttgccccatgaaatgttat
ttcccttttaagctttctgtacagtttgaccgctctgtccatgttgtttggatccccattcccattaagg
gcattctggacaaagcgtctacgctgcagtcctcgctcactgggcacggtgagcgtgaacacaaatccta
aaatccccttagtcagaggtgacaggattggtcttgtctttagccattccatgagtgcctcaagatcggt
gtttttccctgcaaacacatcttcaattctctgcgcgatctcggctttgagggggcctgacgggacgata
gagagaacgtacgtttcgacctcggttagaagactcatctttcaacatctacctgctttactggccgc
.
qlt:
66796788:<;<<<<<=@@79@DCCOEKA@@BGBGDFSMRLNLMLHIGMHHSOQS__SHHPGIEEEFGCH
IFEEGJMKQOR]VVRRRVVMLPHDNN\VVVVV\RVV\VLJJXNVVV\RRSRRVVVVVaaRaVVV\VMWSS
XW\\\VVVV_Y___TV_]V_OVVV\RaTPLTWV]\XXTaXLMRQRRQS__a____\VVMQNSVV__]_VV
_aa]aa\VVVSSLT]a___XVXVPXaX__X_Taa]aaVV\RSVaaaa_VXXXVT]]]TVXT\VVPVXXT_
V__VV_TRRRRM]XaVaVTTPLGKXXWXXIa]aPXXXVXXRRaV____XaRaTPXTPXXTT_V]VTWXLL
]]]TX__aaaLPPNKGGPXRMMMMMXTVXX]TaaVaaaX]]TSRRMRVVVOMMaPLTWXWTWMEGWXXaa
aaaa_YaaaVX]]__]__XTXLXXVXXVTaaRaaaXXRVXTV]\XXWaaaa]aa_]__XTX\\XPXDDBD
>HHKLLXT_TXPXaaaTaaaaaaa]PLLIGH==HHSWXIKNKRRRSXWXXXLLXXXVMSLLDELCC9>
.
clr:9,525
}
{FRG
act:A
acc:1100010858469
typ:R
src:
IWKNA07T08G02MP5F
.
etm:1157567520
seq:
gggatattgagatgagtccttctaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggcctctt
aaagtcgagatcgcgcagagaattgaagaatgtgtttgcagggaaaaacaccgatcttgaggcactcatg
gaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcacgctca
ccgtgcccagtgagcgaggactgcagcgtagacgctttgtccagaatgcccttaatgggaatggggatcc
aaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatggggcaaaa
gaagtggcactcagttattcaaccggtgcacttgccagttgcatgggcctcatatacaacaggatgggga
ctgtgaccactgaagtggcatttggtctagtgtgcgccacgtgtgagcagaatgctgaatcccagcatcg
gtctcacagacaaatggtgacaacaaccaatcccctaatcagacatgaaaacagaatggtggctgctttt
tttcctcccggg
.
qlt:
:8666686::::<?>EADA?<<IPFCCSGGOGICGIGQGGD??>@>GEC?CRRVVTXRNMJPN==66699
9=>9;=C@IIGEINHGCAAEBMMEHK<::<:<>KNQPQQQKPLLLX]]\\VVW]LKKTW__VRV\VRVS\
]VVRRV\\\OOJLNNMLLMOORVaTTSVMVHRTaXPRMRRVVaNIMLSLXXJGJJSRaTVSRRMOLLPPX
\\__]\MVVKQRSVRXaSRVVVRTXXXNMG=<B<=Ta__T]]XLLXXTVX__\WXXXXX___T_VVV\V\
____]]TX\\RSMLLPaaaV________XXXXLL]aa___Y___aTVV_XXXXXT_VTXIIXTX___WWL
LLLMLMMRRXPXLGDGGNNRPXVXTLXPXLWXVTTXLLL]]XPGRVRRJHKLLIFHHEEIPPLPPP\\TT
PPJKKNKFEaTTaLLKP]RPVTVTVRHMLGGKKPGKPGGWXPPPPKGK@:=6:>DG=:66>DTGGLHGML
L]JPLLPGBB=GGHPWWPHHJJJMLXTTPPPTaX_TTV]XAA99DGXXGRPLEDLLEFF>?996668::9
7<6867766677
.
clr:24,529
}
{FRG
act:A
acc:1100010858472
typ:R
src:
IWKNA07T08G03MP252F
.
etm:1140209760
seq:
cggatgcgacgccttatgggatggggaccaacaacatggacagagcggtcaaactgtacagaaagtcaaa
agggaaataacatttcatggggcaaaagaagtggcactcagttattcaaccggtgcacttgccagttgca
tgggcctcatatacaacaggatggggactgtgaccactgaagtggcatttggtctagtgtgcgccacgtg
tgagcagattgctgattcccagcatcggtctcacagacaaatggtgacaacaaccaatcccctaatcaga
cacgagaacagaatggtattggccagtactacggctaaggccatggagcaaatggcagggtcaagtgagc
aggcagcaaaggctatggaggttgctagtcaggccagacagatggtgcaggcaatgaggaccattgggac
tcatcctagctccagtgctggtctaaaagatgatcttcttgaaaatttgcaggcctaccaaaaacggatg
ggggtgcagtctg
.
qlt:
66666666688<CFGCGHMMPRSSBB979:<=HF>DDDHEEEEETSSIIINEIS\\KKKHHEE;877:;=
DHW_ORRQQQVMMHCFCHESNSRVMVPXJGLEGKKD@999=AKHMMPMPJV___VMKKHDDKKHLJJJOO
NNVSS\WVXP]PSMMRVQQQQOR\RRMSRRRXVV\VRR]QBB=<HGWWLLMR\RXXXGLaWPPSXX___]
aaVPXKDDEEKaXTTPPXXXXTTXVVSS\QVVVRRHIKKXXW__\\VVRR]TX]TTXXaaXYYTVSKHBB
MMXLLLLWXXXPXPX\\__________V_XXXPXTTTXXXXXY____XXTTXV\V\_VTVV_____TTT\
RXXPRPH?==DD]TMSMPTMXV\T]]a__VaaTaaPIILLLPLGPXXXXXXRXTXaVXRVX____aYXTX
TTPPXTLIXGHK>A<J]]_a]___VX]IGXLLXTT_VT]VXTV_TT_TTVXPXTV_VMMMMMSRFE;9DD
HD::EAAA67977
.
clr:12,477
}
{FRG
act:A
acc:1100010859003
typ:R
src:
IWKNA07T08G03MP765R
.
etm:1140209760
seq:
cctcgtttctggtagcctgcaattttcagaagatcatcttttagaccagcactggagctaggatgagtcc
caatggtcctcattgcctgcaccatctgtctggcctgactagcaacctccatagcctctgctgcctgctc
acttgaccctgccatttgctccatggccttagccgtagtactggccaataccattctgttctcgtgtctg
attaggggattggttgttgtcaccatttgtctgtgagaccgatgctgggaatcagcaatctgctcacacg
tggcgcacactagaccaaatgccacttcagtggtcacagtccccatcctgttgtatatgaggcccatgca
actggcaagtgcaccggttgaataactgagtgccacttcttttgccccatgaaatgttatttccctttta
agctttctgtacagtttgaccgctctgtccatgttgtttggatccccattcccattaagggcgttctgga
caaagcgtctacactggccgcgttttacaa
.
qlt:
;;999666669:<98:<AAEMLJOHH<9=<@EFLGGGHLMNNCCBDADD@JJGNHQJIQKFEEEDEGB=9
999BFSSVVVS\\SX]XMMMMMPPPPaaaaRRVVVSSSHHGGJWPRVVVOMSSLL]LLTTVTTVVRPVRV
VRMMSRVVV_RRRSMRaV_VSRSRRTa_VVVXX]WXLPLPWPXRVV\V\TVV_TVPaVV_XXXXPa]aPL
HLLMSLNJSRRSVaa___VVXXPVRX\aTaPRXPKBBBKKSaTaRaTaPPT]XLPX]XXVXXVXXTTXXR
aaWXXXLHIHGJ@=FFXXTXRWXV_VXTLLIaWX_]XTXLaX]__XTPLLWWWPSJHICCHK\X]PXRX\
XXX]]\\TXXXXXXVW]KGCM]XPXXPXLLLXXXXXXXPPa]_V_]]XXLGLXWXXVX_V]aaaPa\RSR
MMLTWVXRRP]TXSPaXLXXXXaPaPTRVRVRVa_a]aaXXXXX]aaaaaPWXRPVRXXMWCCWWLLLJL
LVLKCCKMXPPKE>I]X@:7677B@A==FF
.
clr:4,480
}
{FRG
act:A
acc:1100010859004
typ:R
src:
IWKNA07T08G04MP1010R
.
etm:1140209760
seq:
ctttcatgttgaaaatgaccatcgtcaacatccacagcactctgctgttcctgccgatattcttccctca
tagactcaggcactccttccgtagaaggccctcttttcaaaccgtatttaaggcgacgataaatgcattt
gaagaaaagacgatcaagaatccacaatatcaagtgcaagatcccaatgatacttgcggcaataacgaga
ggatcacttgaatcgctgcatctgcactcccatccgtttctggtaggcctgcaaattttcaagaagatca
tcttttagaccagcactggagctaggatgagtcccaatggtcctcattgcctgcaccatctgtctggcct
gactagcaacctccatagcctctgctgcctgctcacttgaccctgccatttgctccatggccttagccgt
agtactggccaataccattctgttctcgtgtctgattaggggattggttgttgtcaccatttgtctgtga
gaccgatgctgggaatcagcaatctgctcacaagtggcacacactaactggccgcgttttttacaa
.
qlt:
9777666::;@77<?@C<<<<<<<<?<@@@@HFABADDJRLM]VLLOLLS\\\_QV\SR\\V___\FBC:
:<<KDGHJKKQQVV_aY]__XXWLLMMVRRVTaa_POROJP\__T_VVRQQQRQHIK<<ADGHM__TY__
XWXLLWXWRRXLXXTWXPSX]_]__Y___VXVXPTT]WRMRRR\V\\VY_____Va]\____]_WXaaaT
JHPPPJ__V__\XXXV_V__V__V]XXTRRRVRMaLLXX___VX_VV\VXVXTTPTW\V\RSJLKGEPKV
__VVWPLLGW]XPXXXXVVRRPXTXPPPPXXX]T]]XXaaaa_]_VVRXXXLLTT__V____aV______
XXTTXVVVX_TVVV\RSaaaLLa]_aaaaPX]\________Y_a]VXPXVaaaVVRRRM]a]a]aaRVXT
XSPXXXV\__]_VV_V_T_a_a_aTVaaRV]XXPRXXVXXMS\VVV____Y_VVX]X____Y_Y__VXXL
LLXTXVXRRa]]TT\XVXXRXX]XX_______VXXV\__]]LLXX]WXRRR@;9678<?>CA>GGH
.
clr:32,515
}
{FRG
act:A
acc:1100010858475
typ:R
src:
IWKNA07T08G04MP461F
.
etm:1140209760
seq:
gggtatgctgagcagattgctgattccagcatcggtctcacagacaaatggtgacaacaaccaatcccct
aatcagacacgagaacagaatggtattggccagtactacggctaaggccatggagcaaatggcagggtca
agtgagcaggcagcagaggctatggaggttgctagtcaggccagacagatggtgcaggcaatgaggacca
ttgggactcatcctagctccagtgctggtctaaaagatgatcttcttgaaaatttgcaggcctaccagaa
acggatgggagtgcagatgcagcgattcaagtgatcctctcgttattgccgcaagtatcattgggatctt
gcacttgatattgtggattcttgatcgtcttttcttcaaatgcatttatcgtcgccttaaatacggtttg
aaaagagggccttctacggaaggagtgcctgagtctatgagggaagaatatcggcaggaacagcagagtg
ctgtggatgttgacgatggtcattttgtcaacatagaattggagtaaaaagtcaagc
.
qlt:
99666666699:;=<>EDB]BBB=<99;;>C@@CEPDCNB@@JGDAAG@@@E>>>AA@CCCCCCCKKKTT
_VEB99@HRVHHMSOQRCQQPNSQRSSSOMOPMPV\\VVV__\VXWRRR\RR\\\\]VR\]V_______Y
_YY_____]VXT]]XGGPPV\Y__]_Y________Y_____]]XRXX_SV\VVVVV_______aVVVVVV
\VVSRS\\\VV\TTVXVXXMGEMaa_____]__\VRR\V\\\V_aa___V\\VSV___Y_____WWTLLW
X_W]RSSWXTV_VXXXXW]VV_____XXXXPWW]__YVXXXX___]VXVTPTLXPXW]W_VV_RV\VVV_
VTTT_V\_TV\VPR\VVSKRT_V_VV_a_]]_]TVVSRMRTXRPVVPR\VTWGLTLLPWTRTTXTLPaVV
TTTRRPRP\TTVTPWTTTWPPTGGPPTRRTTLLKPMKLGGKI]]GLTLLPTPX]LKGKTPPPK]@H;BCL
LTPPVMRHJMMNKHDEBBFKMPTWXTRMJHMSTTLBH::<KKMMMR]_@A87:9977
.
clr:31,521
}
{FRG
act:A
acc:1100010859005
typ:R
src:
IWKNA07T08G05MP1023R
.
etm:1157567520
seq:
aaggtacgttttactccagctctatgttgacaaaatgaccatcgtcaacatccacagcactctgctgttc
ctgccaattttcttccctcaaaaactcaggcactccttccgtaaaaggccctcttttcaaaccgtattta
aggcgacaataaatgcatttgaaaaaaaaacaatcaaaaatccacaatatcaagtgcaaaatcccaatga
tacttgcggcaataacgagaggatcacttgaatcgctgcatctgcactcccatccttttctggtaggcct
gcaaattttcaaaaaaatcatcttttaaaccagcactggagctaggatgattcccaatggtcctcattgc
cggcaccatctgtctggcctgactagcaacctccatagcccctgctgcctgctcacttgaccctgccatt
tgctccagggccttacccgtaactggccgcctttttacaaa
.
qlt:
66669666877:X7=6X688;<=<<89<<9X9@<?>>>=CAA@A?CCFCCCCDAAEAAEBBGKKECBKHL
CA99779;99BCGLGXDA<<99<<C<<BBEBAADBLLKKGA@AEEIHLLIEGGKWHFDJHEJLLGGIXLM
SFFA=BEDD;;;D>ELGPWPGGKDA]MJ;;D<;:<AB<BKFFEBBDKGGHGI>><@GJH@=HBHKJIEEC
CCLLLKLLLLLLLLHHHHHHA??@@AAAKKPLGICKGEELIIGGAAHEAGEB?DHKK]HKEGLLLPGLLC
CLKKDIa]LLWJ<=GADGGGGCKWMGGLEDDE<<>>BHGAAABH<?9;99<<DDXGIAKKKLGIEKKEHH
HD>DDILLLIKKKKKLKKKAAG>>HH>IILKGGG?@FCCKKKKHLKIKKKKKDGA@>JGGXXLLDDB?=I
DLLG>DE<9EHKHHH<:DBBBB@:@J@876778@;?;<DCL
.
clr:10,380
}
{FRG
act:A
acc:1100010858478
typ:R
src:
IWKNA07T08G05MP577F
.
etm:1140209760
seq:
ccgaaactgcagcaatggcacgtcagtgagcaggcagcagaggctatggaggttgctagtcaggccagac
agtaggtgcaggcaatgaggaccattgggactcatcctagctccagtgctggtctaaaagatgatcttct
tgaaaatttgcaggcctaccagaaacggatgggagtgcagatgcagcgattcaagtgatcctctcgttat
tgccgcaagtatcattgggatcttgcacttgatattgtggattcttgatcgtcttttcttcaaatgcatt
tatcgtcgccttaaatacggtttgaaaagagggccttctacggaaggagtgcctgagtctatgagggaag
aatatcggcaggaacagcagagtgctgtggatgttgacgatggtcattttgtcaacatagagctggagta
aaaaactaccttgtttctacgggccaacct
.
qlt:
7877676766688<?AB>=6669;DMPGKIMKKMMNQOHIHVHRHEEEECCCECMMOEOJECCOPJFD<:
77677:=HMKKORKQQMVHJMOOPQQSOQRMQQNNNXXPPKA=99:BMW]_Y____W]SSRRVV\\V]a_
_V_\]RKKKQQQV\T__VSNLJJXWY]VPXX\\WWSPXXPSWXXTTVVV\V\SKKGK\\\\_a]VV\V\\
V_V_PXPPMOOV\VXX]V_Y__________Y_YY___a\V\VVV]VV\\VVaaaaTY_VV\\VSVV__Y_
__Y_aaaPaXT______T__VV_Y_____a____Y___V\VXXPaVVXPX]aa\VRPXXXWLGGaPWT\R
RVVRSRQ\SXRXT__VTWLEEMKXaaaaVV\\\\_XXLLXLLLXX___________TXXaa]aT]XRRXT
]_]M>:@JaaaKLLPHCABA:=66:96686
.
clr:14,420
}
{FRG
act:A
acc:1100010858481
typ:R
src:
IWKNA07T08G06MP1F
.
etm:1140209760
seq:
ggaggatgattttatgatgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcccgtcaggc
ccccctaaagccgagatcgcgcagagaattgaagatgtgtttgcagggaaaaacaccgatcttgaggcac
tcatggaatggctaaagacaagaccaatcctgtcacctctgactaaggggattttaggatttgtgttcac
gctcaccgtgcccagtgagcgaggactgcagcgtagaccctttgtccagaatgcccttaatgggaatggg
gatccaaacaacatggacagagcggtcaaactgtacagaaagcttaaaagggaaataacatttcatgggg
caaaagaagtggcactcagttattcaaccggtgcacttgccagttgcatgggcctcatatacaacaggat
ggggactgtgaccactgaagtggcatttggtctagtgtgcgccacgtgtgagcagattgctgattcccag
catcggtctcacagacaaatggtgacaacaaccaatcccctaatcagacacgagaacagaatggtattgg
ccagtactacggctaaagccatggagcaaatggcagggtcaagtgagcaggcagcaaaagctatggaggt
tgctagtcaggccagacagatggtgcaggcaatgaggaccattgggactcatcctagctccagtgctggt
ctaaaagatgatcttcttgaaaatttgcaggcctaccaaaaacgaatgggggtgcagtctcctttttttt
ctctc
.
qlt:
99977779<;79>777::BBKCDFFJFMKEFHHQIKQTCFF=?CAACCGGEEHGE<<@GEDHLBH:8@<;
;99777>9;DC>B>A=@=CKGG<??FFHD?>H=BBKHQMNMIKDE>>EIJJ]IBGGJAD<<<DDLRRHID
GIEECHHJNMMMKKHHAC@HBCGWDD99DHTV\\\VVT]XXSRMOSRaOOVVVVV\SSV\_______VXR
X\___V]]\VSVXPXXXXTX__VVV\RVaaaRXWG><<99DHY_Y]VXPRTVTTVYY_WWXPWW____YV
V\VVVVV\_]__]aaTXLLLPaa]T______a_XXXXXVV______T\PVX__V]XXT]YT_TWEEGTWX
X\]WLLXXPRTWXTXKKGDJDBFEPIFC]TLLPXLXXPPPXTTXWWLLHRRKVSEJ;>;@E>@:ADNBCH
HPGKHAABGMPHGLXTXXMKKa]PHXH\aaPKaKKKKKaLHPLLXXXJFGCBHG?G>>GGFEKDAGFKQC
IQHKJJDDLLLLE?:7>@FDTLGHG=BAEDJKTLLPHTOOVRRDG;;GJJDB;;GTWGGKCFAE@CEFFC
HHGGPPPED<AA@>>99;;?IAHMFCCACGHMECACCCCHGRLPPGKWE>A99@C:877?<DA>::B@FC
GPXLGLPLGGKGB>>DGD<>;7<HFC>BC;>GBAGCAFAEKPPHHHHHHPGHCB;<??@A87<@?GGPHH
CHHHKTKHB?BAAGGGHTTHCKHHHRHHEECCCCCCCCCGLG@;79::B@AAA<;88:766778=<<879
87776
.
clr:9,735
}
{FRG
act:A
acc:1100010859106
typ:R
src:
IWKNA07T08G06MP765R
.
etm:1140209760
seq:
cttgttttttggtagcctgcaattttcagaagatcatcttttagaccagcactggagctaggatgagtcc
caatggtcctcattgcctgcaccatctgtctggcctgactagcaacctccatagcctctgctgcctgctc
acttgaccctgccatttgctccatggccttagccgtagtactggccaataccattctgttctcgtgtctg
attaggggattggttgttgtcaccatttgtctgtgagaccgatgctgggaatcagcaatctgctcacacg
tggcgcacactagaccaaatgccacttcagtggtcacagtccccatcctgttgtatatgaggcccatgca
actggcaagtgcaccggttgaataactgagtgccacttcttttgccccatgaaatgttatttccctttta
agctttctgtacagtttgaccgctctgtccatgttgtttggatccccattcccattaagggcattctgga
caaagcgtctaccctgcagtcctcgctcactgggcacggtgagcgtgaacacaaatcctaaaatcccctt
agtcagaggtgacaggattggtcttgtctttagccattccatgagtgcctcaagatcggtgtttttccct
gcaaacacatcttcaattctctgcgcgatctcggctttgagggggcctgacgggacgatagagagaacgt
acgtttcgacctcggttagaagactcatctttaaatatctacctgctttcgctactggctccatttttaa
aaa
.
qlt:
779999777778777<<C==DCCCHA===><B=ABBEGTHCHFC?CGKEENJGJVSFHDDCFFEEFD?;9
999>CHS\VRSRRSaaXIDHKMRRNORMVRRRMOMMLMJJJJMXXRVVVRSKKGGLEEXKTXPWWRaNNJ
HHLXXXWWGGBBHACMFJJFBB;>GTa_TTPPX]TXLLLKKLXNROOLM]X_TTXaPTTXRXXPPaaaLL
]PPXPPKHLRMRaaaPXXTXXXXRXPXPPPSSPXKE>>GGLLPaRaT\PPVWTXLLMKLLPPXPTXXRPX
PTaXKKDBCKKKKBIIRRRPP]XVRRKLEEBKKWTXRSSPPT]]RLXaLLa]XTPKIF@@GJWX]RXPPX
XXTVVXXPXPXXT__XaLXEPXXXXPPPLLGXW]XXRTPPa]XXX]]XKLELWXRRVVRPVVXXPPRRRR
SSaaaa_TXTXPLLW]PXVTVRXXXaaLP]XRTX]aaaaRRSRRRX_WWPXWX\XTXXTX\V_X]XaXXL
XPVXXXVXXGMB<<MGXXIGWMaaPXXRTXLPaX]XRXXaaaTTXVXX\]__]]XaaaPX]TXXV_aTPX
LPGMAAIMWTPLLXSRMVHRaaa]TTaaTTTLL]PPRHWXPLPLLLX]TWXJG=GGT]PTPPTTVTTTTT
THT]_TTTHHHBGGHHPHHHHTVTTHHHXTT\THHTTCCCECCHHTHVTPPTHPHDED;<9>HQ\W\RXX
XRSXXXXLLXXXXTCJIHKMPLLTT]PX]TTPTVVHVVHIIDHHIST]HLTHMFF<8;9797999:8:88
77=
.
clr:32,738
}
{FRG
act:A
acc:1100010859107
typ:R
src:
IWKNA07T08G07MP1023R
.
etm:1140209760
seq:
aagattaggttttttctcacctctttttgaaaaatgaccatcgtcaacatccacagcactctgctgttcc
tgccaatattcttcccccaaaaacccaggcactccttccgaaaaaggccctcttttcaaaccgtatttaa
ggcgacaataaatgcatttgaaaaaaaaacaatcaaaaatccccaatatcaagtgcaaaatcccaatgat
acttgcggcaataacaagaggatcacttgaatccctgcatctgccctcccatccttttctggtaggcctg
caaattttcaaaaaaatcatcttttaaaccaccactggagctaggaggagtcccaatggtcctcattgcc
ggcaccatctgtctggcctgacaatcaacctccaaaccccctgctgcctgctcacttgaccctgccattt
gctccagggccttagccgtattactggccaataccattcttttctcgtgtctaattaggggattggttgt
tgtcaccatttgtctgtgaaaccgatgctgggaatcaccaatctgctcacaagtggcacacactaactgg
ccgccctttttaaaaaa
.
qlt:
;976779979=97777776777:;999;>;>B<:::;;:99999<9<<;9?@=:=;=C>=>CCC>@IAC=
<97>99<;D@?KLJD<9999=>=99:?DAAA>>>GK>=9999BDLLLLLGAKKW@DDHF=AAH>A?CCD@
@H<<DEEE=:@D>BBAKaGCAKDCKNKGBE><99<@@CCDDJD@AAB=>BB=:;=DDGBCCBHGKGBA>;
>DJGKBBIIIEEEHE>;;<<>>AB>CCGIEGA<<H>>EGAAAA<<<<<EBD<BHHHHHKHADDEGIKGAB
EGKBEKHEDGGBKHBBBC=@<HJW>>GE??;;9::;CHDDDHD>:9999D<GGIAH<HHHK@<<@@H?H>
><><>D?B=AAABAAKKGCAD:999<>>JB==BC;@HHG@BDEEIH@B;=ADDD>BIGGKKAAGHGLBH;
<::C<D;>HKLIKKKKEAAD;;E<>@GLGJ=@GABGBBDDHHB>:>;;>=>>AGAAEHH=;GGICKKKKG
B>C@<<AAHHHHD;<<><=JDDA<<<<<GHKAAG=??;=DCG@@KBADB==><<BBBAD<<@<><?;;>@
B;867779@@===<A@@
.
clr:113,371
}
{FRG
act:A
acc:1100010858484
typ:R
src:
IWKNA07T08G07MP461F
.
etm:1140209760
seq:
gggtattgtgagcagattgctgattccagcatcggtctcacagacaaatggtgacaacaaccaatcccct
aatcagacacgagaacagaatggtattggccagtactacggctaaggccatggagcaaatggcagggtca
agtgagcaggcagcagaggctatggaggttgctagtcaggccagacagatggtgcaggcaatgaggacca
ttgggactcatcctagctccagtgctggtctaaaagatgatcttcttgaaaatttgcaggcctaccagaa
acggatgggagtgcagatgcagcgattcaagtgatcctctcgttattgccgcaagtatcattgggatctt
gcacttgatattgtggattcttgatcgtcttttcttcaaatgcatttatcgtcgccttaaatacggtttg
aaaagagggccttctacggaaggagtgcctgagtctatgagggaagaatatcggcaggaacagcagagtg
ctgtggatgttgacgatggtcattttgtcaacatagagctggagtaaaaacctacctggttcctacgggc
ccacct
.
qlt:
:9966689::;<=@>?EEAVDHE<<99<<?CBI@PP>ENG@BDA===BFEMBCC@CHCCCCROCCKXKTX
X@>7668DHVHTRSOV\\QQPNOQSSSSPPMMPJ\\V\\VVROMLMMOVVRR\\OQ\RSRW____Y\V\\
V\_V____V\PX]WXGGXX_Y\V\]\\____Y_____Y_\\VOMRVVS__X]XTX]__V___]a\\\\\\
__a\V\\\V]V_XTXVXWWGLKKa]aaaV]V]X\VRR\VV___]aa__Y\\\\VV_Y_______WWTLLW
X_WXLLLW]_Y_]XTXXW]V___Y__V]XXRVR\\\\_aaaV_____V__XWPXX]]]\\___VV\\V\_
______Y____Y_a__________YY_aaaaaa]\V\]VR\V_Y__T__TaaaRa\XRV\_]___a]a__
_TVXRX]Y__YY_TT]_VVXVVVXXTV__\]RaT]TWXLGPPXaRR]TTVVSR]VSRVTYY_TaKKKXPT
\_S\\VVVY_YWWLLXLLXWV_____VVVV\VTWLLLPT]a]XXX]]]]MDDDEBDD99A:<79=I<<:6
676676
.
clr:7,536
}
