package org.jcvi.common.core.seq.read.trace.pyro.sff;

import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import org.jcvi.common.core.Range;
import org.jcvi.common.core.datastore.DataStoreException;
import org.jcvi.common.core.io.IOUtil;
import org.jcvi.common.core.seq.read.trace.pyro.Flowgram;
import org.jcvi.common.core.util.iter.CloseableIterator;
/**
 * 454 includes an optional index at the 
 * end of their {@literal .sff} files that contains
 * and encoded file offset for each record
 * in the file.  The actual format is not 
 * specified in the 454 manual or file specification
 * so it had to be reverse engineered.
 * <p/>
 * This class supports two index encodings.
 * <ol>
 * <li>An XML manifest and sorted index that are generated
 * by 454 programs by default.</li>
 * <li>Just a sorted index without the XML manifest 
 * that can be generated by sfffile using the "-nmft" option.</li>
 * </ol>
 * This class does not work on ion torrent sff files
 * since as of Spring 2012, they don't include an index.
 * @author dkatzel
 *
 */
final class Indexed454SffFileDataStore implements SffDataStore{
	
	/**
	 * Try to create a {@link SffDataStore} by only parsing
	 * the 454 index at the end of the sff file.
	 * If there is no index or it is encoded
	 * in an unknown format, then this method will
	 * return null.
	 * @param sffFile
	 * @return an {@link SffDataStore} if successfully
	 * parsed; or {@code null} if the index can't
	 * be parsed.
	 * @throws IOException if there is a problem reading the file.
	 */
	public static SffDataStore create(File sffFile) throws IOException{
		ManifestCreatorVisitor visitor = new ManifestCreatorVisitor(sffFile);
		SffFileParser.parseSFF(sffFile, visitor);
		if(!visitor.isUseableManifest()){
			//no manifest delegate to iterating thru
			return null;
		}
		return new Indexed454SffFileDataStore(visitor);
	}
	private final File sffFile;
	private SffCommonHeader commonHeader;
	private Map<String, Integer> map;
	private boolean isClosed=false;
	
	
	private Indexed454SffFileDataStore(ManifestCreatorVisitor visitor){
		this.map = visitor.map;
		this.sffFile = visitor.sffFile;
		this.commonHeader = visitor.commonHeader;
	}
	@Override
	public CloseableIterator<String> getIds() throws DataStoreException {
		throwErrorIfClosed();
		try {
			//use large sffFileDataStore 
			//to parse ids in order in file
			return LargeSffFileDataStore.create(sffFile).getIds();
		} catch (FileNotFoundException e) {
			throw new IllegalStateException("sff file has been deleted");
		}
	}

	@Override
	public Flowgram get(String id) throws DataStoreException {
		throwErrorIfClosed();
		Long offset = getOffsetFor(id);
		if(offset ==null){
			return null;
		}
		
		SffFileVisitorDataStoreBuilder builder = DefaultSffFileDataStore.createVisitorBuilder();
		builder.visitFile();
		InputStream in=null;
		try {
			in = new FileInputStream(sffFile);
			IOUtil.blockingSkip(in, offset);
			DataInputStream dataIn = new DataInputStream(in);
			 SffReadHeader readHeader = DefaultSffReadHeaderDecoder.INSTANCE.decodeReadHeader(dataIn);
			 final int numberOfBases = readHeader.getNumberOfBases();
             SffReadData readData = DefaultSffReadDataDecoder.INSTANCE.decode(dataIn,
                             commonHeader.getNumberOfFlowsPerRead(),
                             numberOfBases);
             builder.visitReadHeader(readHeader);
             builder.visitReadData(readData);
             return builder.build().get(id);
		} catch (IOException e) {
			throw new DataStoreException("error trying to get flowgram "+ id);
		}finally{
			IOUtil.closeAndIgnoreErrors(in);
		}
	}
	/**
	 * Get the offset into the sff file from the manifest.
	 * @param id the read id to get.
	 * @return Returns offset into sff file which contains the start
	 * of the given record or null if there is no read
	 * with that name in the manifest.
	 */
	private Long getOffsetFor(String id){
		Integer offset= map.get(id);
		if(offset ==null){
			return null;
		}
		return IOUtil.toUnsignedInt(offset.intValue());
	}
	@Override
	public boolean contains(String id) throws DataStoreException {
		throwErrorIfClosed();
		return map.containsKey(id);
	}

	@Override
	public int size() throws DataStoreException {
		throwErrorIfClosed();
		return map.size();
	}

	@Override
	public synchronized boolean isClosed() throws DataStoreException {
		return isClosed;
	}

	@Override
	public CloseableIterator<Flowgram> iterator() {
		throwErrorIfClosed();
		try {
			return LargeSffFileDataStore.create(sffFile).iterator();
		} catch (FileNotFoundException e) {
			throw new IllegalStateException("sff file has been deleted");
		}
	}

	@Override
	public synchronized  void close() throws IOException {
		isClosed =true;
		map.clear();
		
	}
	
	private synchronized void throwErrorIfClosed(){
		if(isClosed){
			throw new IllegalStateException("closed");
		}
	}

	private static final class ManifestCreatorVisitor implements SffFileVisitor{
		/**
		 * 255 ^ 3 = {@value}.
		 */
		private static final int POW_3 = 16581375;
		/**
		 * 255 ^ 2 = {@value}.
		 */
		private static final int POW_2 = 65025;
		/**
		 * 255 ^ 1 = {@value}.
		 */
		private static final int POW_1 = 255;
		
		private final File sffFile;
		private SffCommonHeader commonHeader;
		private Map<String, Integer> map;
		private boolean useableManifest=false;
		private ManifestCreatorVisitor(File sffFile) {
			this.sffFile = sffFile;
			
		}
		@Override
		public void visitFile() {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void visitEndOfFile() {
			// TODO Auto-generated method stub
			
		}

		public boolean isUseableManifest() {
			return useableManifest;
		}
		

		@Override
		public CommonHeaderReturnCode visitCommonHeader(SffCommonHeader commonHeader) {
			this.commonHeader = commonHeader;
			BigInteger offsetToIndex =commonHeader.getIndexOffset();
			if(offsetToIndex.longValue() !=0L){
				tryToParseManifest(commonHeader, offsetToIndex);
			}
			//stop parsing file
			return CommonHeaderReturnCode.STOP;
		}

		private void tryToParseManifest(SffCommonHeader commonHeader,
				BigInteger offsetToIndex) {
			long indexLength =commonHeader.getIndexLength();
			InputStream in=null;
			try {
				in = IOUtil.createInputStreamFromFile(sffFile, Range.createOfLength(offsetToIndex.longValue(),indexLength));
				
			    //pseudocode:
				//skip xml manifest if present
				//read bytes until byte value is 0
				//anything before the 0 is the read name
				//next 4 bytes? is offset into file using base 255
				//offset also appears to be in little endian
				//another null byte separator before next entry

				byte[] magicNumber =new byte[4];
				IOUtil.blockingRead(in, magicNumber);
				if(Arrays.equals(magicNumber, ".mft".getBytes(IOUtil.UTF_8))){
					//includes xml plus sorted index
					byte[] version = new byte[4];
					IOUtil.blockingRead(in, version);
					String versionString = new String(version, IOUtil.UTF_8);
					if(!"1.00".equals(versionString)){
						throw new IOException("unsupported xml manifest version : " + versionString);
					}
					long xmlLength =IOUtil.readUnsignedInt(in);
					//skip 4 bytes for the datalength
					IOUtil.blockingSkip(in, 4 + xmlLength);
					//System.out.println("sorted manifest\n" + IOUtil.toString(in, IOUtil.UTF_8_NAME).replaceAll("\0", "\\0") + "\n<end of sorted>");
					populateOffsetMap(in); 
					useableManifest=true;
				}
				//this kind of index is created
				//by sfffile if you say "no manifest"
				if(Arrays.equals(magicNumber, ".srt".getBytes(IOUtil.UTF_8))){
					//includes xml plus sorted index
					byte[] version = new byte[4];
					IOUtil.blockingRead(in, version);
					String versionString = new String(version, IOUtil.UTF_8);
					if(!"1.00".equals(versionString)){
						throw new IOException("unsupported sorted manifest version : " + versionString);
					}
					
					
					//System.out.println("sorted manifest\n" + IOUtil.toString(in, IOUtil.UTF_8_NAME).replaceAll("\0", "\\0") + "\n<end of sorted>");
					populateOffsetMap(in); 
					useableManifest=true;
				}
			
			} catch (IOException e) {
				throw new RuntimeException("error parsing manifest", e);
			}finally{
				IOUtil.closeAndIgnoreErrors(in);
			}
		}

		private long convertFromBase255(byte[] values){
			long sum= IOUtil.toUnsignedByte(values[0]) + POW_1*IOUtil.toUnsignedByte(values[1])+ POW_2*IOUtil.toUnsignedByte(values[2]) + POW_3*IOUtil.toUnsignedByte(values[3]);
			return sum;
		}
		private void populateOffsetMap(InputStream in) throws IOException {
			map = new HashMap<String, Integer>((int)commonHeader.getNumberOfReads()+1, 1F);
			for(long i =0; i< commonHeader.getNumberOfReads(); i++){
				String id = parseNextId(in);
				if(id ==null){
					throw new IOException(
							String.format("incomplete index in sff file; missing %d reads",commonHeader.getNumberOfReads()-i));
				}
				byte[] index = new byte[4];
				IOUtil.blockingRead(in, index);
				index =IOUtil.switchEndian(index);
				long offset =convertFromBase255(index);
				//signed int to save space
				map.put(id,IOUtil.toSignedInt(offset));
				in.read();//skip
			}
		}

		private String parseNextId(InputStream in) throws IOException {
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			byte nextByte =(byte)in.read();
			if(nextByte==-1){
				return null;
			}
			do{
				out.write(nextByte);
				nextByte =(byte)in.read();
			}while(nextByte !=0);
			return new String(out.toByteArray(), IOUtil.UTF_8);
		}

		@Override
		public ReadHeaderReturnCode visitReadHeader(SffReadHeader readHeader) {
	
			return ReadHeaderReturnCode.STOP;
		}

		@Override
		public ReadDataReturnCode visitReadData(SffReadData readData) {
			return ReadDataReturnCode.STOP;
		}
		
	}
}
