package org.jcvi.common.core.assembly.tasm;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.jcvi.common.core.datastore.DataStoreException;
import org.jcvi.common.io.fileServer.FileServer;
import org.jcvi.common.io.fileServer.ResourceFileServer;
import org.junit.Test;
import static org.junit.Assert.*;
public class TestAnnotationTasmParsing {
	 private static final FileServer RESOURCES = new ResourceFileServer(TestAnnotationTasmParsing.class);
	 
	 private final DefaultTigrAssemblerFileContigDataStore datastore;
	 public TestAnnotationTasmParsing() throws FileNotFoundException, IOException{
		 datastore = new DefaultTigrAssemblerFileContigDataStore(RESOURCES.getFile("files/annotation.tasm"));
			
	 }
	 @Test
	 public void numberOfContigs() throws DataStoreException{
		 assertEquals(3L, datastore.getNumberOfRecords());
	 }
	 @Test
	 public void correctContigIds() throws IOException, DataStoreException{
		 assertTrue(datastore.contains("1122071329926"));
		 assertTrue(datastore.contains("1122071329927"));
		 assertTrue(datastore.contains("1122071329928"));
		 
	 }
	 
	 @Test
	 public void contigEndingIn927() throws DataStoreException{
		 String gappedConsensusOf927 = 
				 "GAATGGATGTCAATCCGACTTTACTTTTCCTGAAAGTTCCAGCGCAGAATGCCAT" +
				 "AAGCACCACATTCCCTTATACTGGAGATCCTCCATACAGCCATGGAACGGGAACA" +
				 "GGATACACCATGGACACAGTCAACAGGACACATCAATATTCAGAAAAGGGGAAAT" +
				 "GGACAACAAACACAGAGACTGGGGCACCCCAACTCAACCCAATCGATGGACCACT" +
				 "GCCCGAAGACAATGACCCAAGTGGATATGCACAAACAGACTGTGTCCTTGAAGCA" +
				 "ATGGCTTTCCTTGAAGAGTCCCACCC-AGGAATCTTTGAAAACTCGTGTCTTGAA" +
				 "ACGATGGAAGTTGTCCAACAAACAAGAATGGACAAACTGACCCAGGGTCGTCAGA" +
				 "CCTATGATTGGACTTTAAACAGGAATCAGCCGGCTGCAACTGCATTAGCCAATAC" +
				 "TATAGAGGTCTTCAGATCGAATGGTCTGACAGCTAATGAATCAGGAAGGCTGATA" +
				 "GATTTCCTCAAGGATGTGATGGAATCAATGGATAAAGAGGGAATGGAAATAACAA" +
				 "CGCACTTCCAAAGAAAGAGAAGAGTAAGAGACAACATGACCAAGAAAATGGTCAC" +
				 "ACAAAGGACAATAGGAAAGAAGAAGCAAAGGCTGAACAAGAAAAGCTATCTAATA" +
				 "AGAGCATTGACACTAAACACAATGACCAA-AGATGCTGAAAGAGGCAAATTAAAG" +
				 "AGGAGAGCAATTGCTACACCCGGAATGCAGATCAGAGGATTTGTATACTTTGTTG" +
				 "AAACATTAGCGAGGAGCATCTGTGAGAAGCTTGAACAATCTGGACTCCCAGTTGG" +
				 "AGGCAATGAAAAGAAGGCTAAACTGGCAAACGTTGTAAGAAAAATGATGACTAAT" +
				 "TCACAAGACACAGAACTCTCCTTCACTATCACCGGAGACAACACCAAATGGAATG" +
				 "AGAATCAGAACCCTAGGATGTTTCTGGCAATGATAACATACATAACAAGGAACCA" +
				 "ACCTGAGTGGTTTAGGAATGTCTTGAGCATTGCACCTATAATGTTCTCGAATAAA" +
				 "ATGGCA-AGACTAGGGAAGGGATACATGTTCGAAAGCA-AGAGCATGAAGCTTAG" +
				 "AACACAGATACCAGCAGAAATGCTAGCAAGTATTGATCTAAAATATTTCAATGAG" +
				 "TCAACAAGAAAGAAAATAGAGAAGATAAGGCCTCTTCTAATAGATGGTACAGCTT" +
				 "CATTGAGCCCTGGAATGATGATGGGCATGTTCAACATGCTAAGTACAGTTTTGGG" +
				 "AGTCTCGATTCTCAACCTAGGGCAGAAGAGGTACACCAAAACAACATATTGGTGG" +
				 "GACGGACTCCAATCCTCCGATGACTTTGCTCTTATAGTGAATGCTCCGAATCATG" +
				 "AAGGAATACAAGCAGGAGTAGATAGATTCTATAGAACCTGCAAGCTGGTCGGAAT" +
				 "AAATATGAGCAAAAAGAAGTCCTACATAAACAAGACAGGGACATTTGAATTCACA" +
				 "AGCTTTTTCTATCGCTATGGATTTGTAGCCAATTTTAGCATGGAGCTTCCCAGTT" +
				 "TTGGAGTGTCTGGGATTAATGAATCTGCTGACATGAGCATTGGAGTAACAGTGAT" +
				 "AAAGAACAACATGATAAACAATGATCTTGGACCAGCAACAGCTCAAATGGCTCTT" +
				 "CAGCTATTCATCAAGGATTACAGATACACGTATCGGTGCCACAGAGGGGACACAC" +
				 "AAATTCAAACAAGGAGGTCATTCGAGCTGAAGAAGTTGTGGGAACAAACCCGCTC" +
				 "AAAGGCAGGACTGCTGGTTTCAGATGGAGGGCCAAACTTATACAATATCCGAAAT" +
				 "CTCCACATCCCGGAGGTCTGCCTGAAATGGGAGCTGATGGACGAAGATTATCAGG" +
				 "GAAGGCTTTGTAACCCCCTGAATCCATTTGTCAGCCACAAAGAGATAGAGTCTGT" +
				 "AAACAATGCTGTGGTGATGCCAGCTCATGGCCCAGCCAAGAGCATGGAATATGAT" +
				 "GCTGTTGCTACCACGCACTCCTGGATCCCTAAGAGGAACCGCTCCATTCTCAACA" +
				 "CAAGCCAAAGGGGAATCCTTGAAGATGAACAGATGTATCAGAAATGCTGCAATCT" +
				 "ATTCGAGAAATTCTTCCCTAGCAGCTCATACAGGAGACCGGTTGGAATTTCCAGC" +
				 "ATGGTGGAGGCCATGGTTTCTAGGGCCCGAATTGATGCGAGAATTGACTTCGAAT" +
				 "CTGGACGGATTAAGAAGGAGGAGTTTGCTGAGATCATGAAGATCTGTTCCACCAT" +
				 "TGAAGAGCTCAGACGGCAGAAATAGTGAATTTAGCTTGTCCTTCATG";
		 
		 TigrAssemblerContig contig = datastore.get("1122071329927");
		assertEquals(gappedConsensusOf927, contig.getConsensusSequence().toString());
	 }
}
