/*
 * Created on Sep 1, 2009
 *
 * @author dkatzel
 */
package org.jcvi.trace.sanger.traceArchive;

import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;

import org.jcvi.IdConverter;
import org.jcvi.datastore.DataStoreException;
/**
 * {@code DefaultTraceNameConverter} maps 
 * a TraceArchiveInfo's trace_name to id
 * generated by the given {@link TraceArchiveRecordIdGenerator}.
 * @author dkatzel
 *
 *
 */
public class DefaultTraceNameConverter implements IdConverter<String,Long> {
    private final Map<String, Long> map;
    
    /**
     * Iterate over the given traceInfo and map all it's trace_name's
     * to the id generated by the given {@link TraceArchiveRecordIdGenerator}.
     * @param traceInfo the traceInfo to examine.
     * @param traceIdGenerator the generator used to generate IDs.
     * @throws DataStoreException if there is a problem reading the traceInfo.
     */
    public DefaultTraceNameConverter(TraceArchiveInfo traceInfo, TraceArchiveRecordIdGenerator traceIdGenerator ) throws DataStoreException {
        map = new HashMap<String, Long>(traceInfo.size());
        for(TraceArchiveRecord record : traceInfo){
            String traceId = traceIdGenerator.generateIdFor(record);
            Long traceName = Long.parseLong(record.getAttribute(TraceInfoField.TRACE_NAME));
            map.put(traceId, traceName);
        }
    }

    @Override
    public Long convertId(String id) {
        if(map.containsKey(id)){
            return map.get(id);
        }
        throw new NoSuchElementException(String.format("trace name with id %s not found", id));
    }

}
