/*
 * Created on Feb 3, 2010
 *
 * @author dkatzel
 */
package org.jcvi.fasta;

import java.io.File;
import java.io.IOException;

import org.jcvi.datastore.DataStore;
import org.jcvi.glyph.nuc.NucleotideEncodedGlyphs;

public  abstract class AbstractTestSequenceFastaDataStoreWithNoComment {
    static final String FASTA_FILE_PATH = "files/noComment.fasta";

DefaultEncodedNucleotideFastaRecord hrv_61 = new DefaultEncodedNucleotideFastaRecord("hrv-61",null,
        "TTAAAACTGGGTCTGGGTTGCTCCCACCCAGACCACCCATGTGGTGTTGTACACTGTTAT" +
        "TCCGGTAACTTTGTACGCCAGTTTTGAACTCCCCTACCCCTTTTGTAACTTAGAAGCTAA" +
        "ACACATCGACCAATAGCAGGCAATCACCCAGATTGCTTATGGTCAAGTACTTCTGTTTCC" +
        "CCGGTCTCCTCTGATATGCTCTACCAGGGCAAAAACAGAGTAGATCGTTATCCGCAAGAT" +
        "GCCTACGCAACGCCTAGTAACACTTTGAAGTGTTTTTGGTTGGTCGCTCAGTTACAACCC" +
        "CAGTAATAGACCTGGCAGATGAGGCTAGATATCCCCCACTGGCGACAGTGATCTAGCCTG" +
        "CGTGGCTGCCTGCACACCCTTTATGGGTGTGAAGCCAAACATATGACAAGGTGCGAAGAG" +
        "CCACGTGTGCTCATCTTGAGTCCTCCGGCCCCTGAATGCGGCTAACCTCAACCCTGCAGC" +
        "CATTGCTCACAAGCCAGTGGGTATGTGGTCGTAATGAGAAATTGCGGGACGGGACCGACT" +
        "ACTTTGGGTGTCCGTGTTTCACTTTTTTACCTTATTTTGCTTATGGTGACAATATATATA" +
        "CAGATATATATTGACACCATGGGCGCTCAGGTATCCAGACAAAACGTTGGTACTCATTCT" +
        "ACTCAGAATTCTGTTTCAAATGGTTCTAGTTTAAACTATTTTAACATTAATTACTTTAAA" +
        "GATGCGGCTTCAAGTGGAGCATCCAAATTGGAATTTTCACAAGACCCCAGCAAATTTACA" +
        "GATCCAGTCAAGGATGTTTTAGAGAAGGGAATACCAACTCTACAATCACCAACTGTTGAA" +
        "GCATGTGGTTATTCAGATAGAATCATCCAAATTACAAGAGGTGACTCCACAATTACCTCA" +
        "CAAGATGTTGCTAATGCTGTAGTTGGGTATGGAGTTTGGCCACATTACTTAACACCACAA" +
        "GATGCCACTGCTATAGATAAACCTTCTAAGCCTGACACATCTTCTAATAGATTTTACACA" +
        "TTAGAAAGCCAGACCTGGACCAATGAATCCAAGGGCTGGTGGTGGAAATTACCAGATGCT" +
        "TTGAAAGACATGGGTATTTTTGGAGAAAACATGTTTTACCATTTTCTAGGCAGAAGTGGA" +
        "TACACGGTTCATGTCCAGTGCAACGCCAGCAAGTTTCATCAGGGAACTCTTCTGGTAGCA" +
        "ATGATACCAGAGCACCAGCTAGCTACCGCTGTAGGCGGCAGTGTATCTGCAGGATACAAT" +
        "TACACACACCCTGGTGAAAAGGGTAGGGATGTTGGAAAATTAAACCGTGAATCCAATCCA" +
        "AGACAACCTAGTGATGACAATTGGTTAAATTTTGATGGCACATTATTAGGAAACTTGACA" +
        "ATATTTCCTCACCAATTCATTAACCTTAGAAGTAACAACTCGGCTACTATTATAGTACCA" +
        "TATGTTAATGCTGTCCCAATGGATTCAATGCTAAGGCACAATAATTGGAGTTTAGTCATC" +
        "ATACCCATTTGTGAGCTTAGAGGTAGCGGTGTTGATCTCACCATCCCTATTACAATTTCC" +
        "ATTAGTCCTATGTGTGCTGAATTCTCTGGAGCAAGAGCAAACAGCCAGGGGTTGCCGGTC" +
        "TTACTAACACCCGGTTCTGGCCAATTCATGACAACAGATGATTTTCAATCTCCCAGTGCT" +
        "CTACCCTGGTACCATCCTACCAAGGAAATTTCAATACCTGGACAGGTTAGAAATCTAGTG" +
        "GAATTATGCCAAGTAGATACCTTGATACCAATTAACAACACAGAAGCCAACATCAGAAAT" +
        "AAAAATATGTACACCGTACAACTTGGTGGTGAACCTGACCCTACAACCCCGGTTTTCACA" +
        "ATTAGGGTTGATATTGCATCACAACCATTAGCCACTACACTTATAGGTGAAGTTTCCAGC" +
        "TACTACACACATTGGACTGGGAGTGTTAGATTTAGTTTTATGTTCTGTGGATCAGCACTT" +
        "ACAACACTAAAGTTATTGATTGCATATACCCCACCTGGTATTAGAGTTCCAAGAAATAGA" +
        "AAAGAAGCAATGCTTGGTACACATCTAATATGGGACGTTGGTCTACAGTCCACAGTGTCA" +
        "ATGGTGGTTCCCTGGGTCAGTGCTAGTCATTATAGAAACACAACCCCAGATACATATTCA" +
        "ATAGCTGGCTTCATTACATGCTGGTATCAAACAAAACTGGTAGTTCCCCCAAACACAGCC" +
        "TCCACAGCTGATATGCTGTGCTTTGTTTCAGGGTGCAAAGATTTCTGCCTACGCATGGCA" +
        "AGAGATACTAACTTACACAAGCAAAGTGGACCTATTGAGCAAAACCCTGTGGAAAGATAT" +
        "GTAGATGAAGTTTTAAATGAAGTGCTTGTAGTCCCAAACATTAATCAGAGCAACCCTACA" +
        "ACATCCAACTCAGCACCAGTCTTAGACGCTGCTGAAACAGGTCATACCAGCAATGTTCAA" +
        "CCGGAGGACATGATTGAAACACGATATGTTCAAACCTCACAGACAAGAGATGAAATGAGT" +
        "GTAGAAAGTTTCTTGGGTAGATCAGGGTGCATACATATGTCAACATTAAATATAAACTAT" +
        "GATAACTATGATGATTCTATTGAAAACTTCAAGGTGTGGAAAATAAACCTGCAAGAGATG" +
        "GCACAAATACGTAGAAAATTTGAGTTGTTCACATATGCTAGATTTGATTCAGAGATTACA" +
        "ATTGTACCTTGTGTTGCTGGGCAAGGTGGTGACATTGGACACGTGGTCATGCAATACATG" +
        "TATGTTCCACCTGGTGCACCTACACCTGAGAAAAGAAATGATTTCACATGGCAATCAGGC" +
        "ACAAATGCATCTGTTTTCTGGCAACATGGTCAAGCTTATCCCAGATTTTCATTACCATTC" +
        "CTAAGTATTGCATCTGCATATTATATGTTTTATGATGGTTATGATGGAGATTCTGAAATA" +
        "ACGCGCTATGGAACATCAGTGACAAATGATATGGGTGCATTGTGCTTTAGAATAGTAACT" +
        "GAACAGCATACAAATCAAGTTAAAATCACAACTAGGATTTACCATAAAGCTAAACATGTT" +
        "AAAGTCTGGTGTCCTAGACCCCCCAGAGCAGTGGAATATACTAATGTGCATTTGACCAAT" +
        "TACAAGCCCAAAGATAGTGAAAAACAAGTTACCACTTTCATCAAACCTAGAGCTAACTTA" +
        "AGAGAGATTAGAACATTTGGGCCCAGTGACATGTATGTGCATGTCGGAAATTTAATATAT" +
        "AGAAATCTGCACTTATTTAATTCAGAGGCACATGATTCTGTATTAGTATCCTACTCATCA" +
        "GATTTAGTCATTTACCGCACAAACACCGTAGGTGATGACTTTATACCAACATGTGATTGC" +
        "ACACAAGCTACATATTATTGTAAGCACAAAAACAGGTACTTCCCAATCACAGTCACTAGT" +
        "CATGATTGGTACGAAATCCAAGAGAGTGAATATTATCCAAAACATATTCAATATAATCTA" +
        "TTAATTGGTGAGGGTCCTTGTGAACCAGGTGATTGTGGAGGGAAGTTACTGTGTAAACAT" +
        "GGAGTCATTGGCATTATAACTGCTGGTGGTGAAGGGCATGTTGCCTTCATAGATTTAAGA" +
        "CATTTCCTGTGTGCTGAAGAGCAAGGAGTAACAGATTATATCCACATGTTAGGTGAGGCT" +
        "TTTGGAAATGGCTTTGTAGATAGTGTTAAAGAACATGTGAATGCTATAAATCCTGTAAAT" +
        "AATATTAGTAAAAAAGTAATTAAGTGGTTGTTGAGAATTGTATCTGCTATGGTTATAATA" +
        "ATCAGAAACTCATCTGATCCCCAAACCGTTGTTGCCACTTTAACATTAATTGGATGTTCT" +
        "GGGTCACCATGGAGATTCTTAAAAGAAAAATTCTGTAAATGGACCCAACTAACTTACATT" +
        "CATAAAGAATCTGATTCTTGGCTCAAAAAATTCACCGAAATGTGCAATGCAGCAAGAGGA" +
        "CTTGAATGGATAGGGAATAAAATATCAAAATTTATAGAATGGATGAAATCAATGTTGCCA" +
        "CAAGCACAGCTTAAAGTTAAATATTTAAATGAGTTGAAAAAATTAAACCTTCTTGAAAAG" +
        "CAGATTGAGAACCTGAGAAGTGCTGATTCTAAAACTCAAGAAAGGATTAAGGTTGAGATA" +
        "GACACATTACATGATTTGTCCTGTAAATTTCTTCCACTTTATGCTAGTGAAGCCAAGAGG" +
        "ATCAAGGTGATACACAATAAATGTAATACTATCATAAAACAAAAGAAAAGGAGTGAACCG" +
        "GTTGCAGTGATGATACATGGTTCACCAGGTACTGGAAAATCCATAACAACAAATTTTCTG" +
        "GCAAGAATGATAACAAATGAGAGTGACATATATTCATTACCACCTGATCCTAAATATTTT" +
        "GATGGGTACGATCAGCAGTCTGTTGTCATAATGGATGATATCATGCAAAATCCAGATGGT" +
        "GAAGACATGGCACTATTTTGTCAGATGGTCTCTAGTGTAACTTTTATACCCCCAATGGCT" +
        "GATTTACCTGATAAAGGAAAACCCTTTGACTCCAGATTTGTTCTTTGCAGTACTAACCAC" +
        "TCCATGTTGGCCCCTCCAACAATTACATCCCTTCAGGCAATGAATAGACGCTTCTTTCTT" +
        "GATTTAGATATTGTGGTACATGATAATTACAAAGATTCACAAGGGAAACTAAATGTGTCT" +
        "AAAGCTTTTAAACCATGTGATGTTGGAACAAAAATAGGTAACGCACGTTGTTGTCCATTC" +
        "ATTTGTGGCAAGGCAGTTACATTCAAAGATCGCAACACGTGCTTGAGCTACCCATTGAGT" +
        "CAAATTTACAACCTAATTCTCCAAGAGGACAAGAGGCGTACTCATGTTGTAGATGTTATG" +
        "TCTGCTATATTTCAGGGACCAATCTCTATGGAAGTACCTCCTCCTCCTGCAATAACTGAT" +
        "TTGCTCCGATCTGTTAAGACACCTGAAGTTATTAAATATTGTGAAGACAATAAATGGACC" +
        "ATTCCAGCTGATTGTAAGATTGAGAGGGACTTAATTCTTGCTAACAACATTATTACAATT" +
        "ATAGCAAACATAATTAGCATAGCAGGTATTATCTACATTATATATAAACTATTTTGCTCA" +
        "TTTCAAGGACCATACTCTGGTGAACCCAAACCTAAAACAAAAATTCCTGAGAGGAGAGTT" +
        "GTGACACAGGGTCCTGAGGAAGAGTTTGGTCGCTCCCTGATCAAACATAACACTTGTGTG" +
        "GTGACCACTGATAATGGAAAATTTACTGGATTGGGCATTTATGACAAACTCATGATTTTA" +
        "CCCACCCATGCTGACCCTGGAAAAGAAATTTACATCAATGGGATTGCAACAAGGGTCAGT" +
        "GATTCATATGATATGTACAATAAACAAGGAATTAAACTAGAGATTACAGCTGTACTATTG" +
        "GATAGGAATGAAAAATTTAGAGACATTAGGAGATATATACCAGAGAGGGAAGATGATTAC" +
        "CCTGAGTGTAACCTAGCACTGGTAGCAAATCAGCCTGAACCAACTATCATAAGTGTGGGT" +
        "GATGTCATTTCTTACGGCAATATATTGCTTAGTGGCAACCAAACAGCACGCATGCTTAAA" +
        "TACAACTATCCCACAAAATCTGGGTACTGTGGTGGAGTCTTGTACAAAATAGGGCAAATT" +
        "ATAGGGATACATGTGGGTGGAAATGGTAGAGATGGATTTTCAGCAATGTTACTTAGGTCC" +
        "TATTTTAGTGAAACTCAGGGTGAAATCATTACATCAAAGAAAGTTCATGAATGTGGGTAT" +
        "CCAACTATACACACCCCTGCAAAAACAAAGTTACAGCCTAGTGTTTTCTTTGATGTGTTT" +
        "GAAGGTTCAAAAGAACCAGCAGTGCTCACAGAAAAGGATCCCCGTTTAACAACTGATTTT" +
        "AATCAAGCCTTATTTTCCAAATACAAAGGAAATGTTGAATGCAACATGTCTGAACACATG" +
        "AAGGTTGCCATATCACATTATTCTGCTCAATTAATGACTTTAGATATAGACCCTAGCAAT" +
        "ATAACCCTAGAGGAGAGTGTGTTTGGCACTGAAGGTTTGGAAGCTCTCGATCTAAATACT" +
        "AGTGCAGGTTTCCCATACATTAGCATGGGTATCCGAAAGAGAGATTTAATAAACAATAGT" +
        "ACAAAAGATATCACCAAGTTAAAAGTGGCCCTTGACAAGTATGGAGTTGATTTACCTATG" +
        "GTAACATTCCTTAAAGATGAACTCAGAAAGAAAGGAAAAATCATGGCTGGCAAAACAAGA" +
        "GTCATTGAAGCAAGCAGTATCAACGATACAGTTGCTTTCAGAATGACATATGGTAAACTC" +
        "TTCTCTAGTTTCCATAAAAACCCAGGGATCATCACAGGTTCAGCGGTAGGATGTGATCCC" +
        "GAAACATTTTGGTCAAAAATCCCAGTTATGCTCGATGGGGAGTGCATAATGGCATTTGAT" +
        "TACACTAATTATGATGGTAGTATACATCCCATCTGGTTTGAAGCACTCAAACAAGTTCTC" +
        "ATAAATTTATCCTTTGAGCATAGGTTAATAGACAGGTTATGTAAATCAAAACACATATTC" +
        "AAGGACACTTACTATGAAGTTGAAGGGGGGGTACCGTCAGGATGTTCTGGCACTAGTATT" +
        "TTTAATACAATGATTAACAATGTAATAATAAGAACTCTAGTCCTTGATGCATACAAATAT" +
        "ATAGATTTAGATAAGCTTAAAATAATAGCATATGGTGATGATGTCATCTTCTCTTACAAA" +
        "TACCCTCTGGATATGGAAGCAATTGCTGCAGAAGGAAACAAGTATGGTTTAACAATCACA" +
        "CCAGCTGACAAGTCTGATACCTTCAAGAAGCTTGATTACAGCAGTGTTACATTCTTGAAG" +
        "AGAGGTTTCAAACAAGATGACAAATATTCTTTTTTGATTCATCCTACTTTTCCAATTTCT" +
        "GAAATACATGAATCAATTAGGTGGACTAAGAAGCCCTCACAAATGCAGGAACACGTACTA" +
        "TCCTTGTGTCACTTAATGTGGCATAATGGCCGGGATGTGTATAAAGAATTCGAAAGGAAA" +
        "ATACGCAGTGTTAGCGCTGGACGTGCACTGTATATTCCTCCTTACGATCTCCTGTTGCAT" +
        "GAGTGGTATGAAAAATTTTAATATATAGAAATAATAAACAATTAGTTTCTTAGTTTTAT" );



protected abstract DataStore<NucleotideSequenceFastaRecord<NucleotideEncodedGlyphs>> buildMap(File file) throws IOException;
}
