/*******************************************************************************
 * Jillion development code
 * 
 * This code may be freely distributed and modified under the
 * terms of the GNU Lesser General Public License.  This should
 * be distributed with the code.  If you do not have a copy,
 *  see:
 * 
 *          http://www.gnu.org/copyleft/lesser.html
 * 
 * 
 * Copyright for this code is held jointly by the individual authors.  These should be listed in the @author doc comments.
 * 
 * Information about Jillion can be found on its homepage
 * 
 *         http://jillion.sourceforge.net
 * 
 * Contributors:
 *     Danny Katzel - initial API and implementation
 ******************************************************************************/
/*
 * Created on Feb 3, 2010
 *
 * @author dkatzel
 */
package org.jcvi.jillion.fasta.nt;

import java.io.File;
import java.io.IOException;

import org.jcvi.jillion.core.datastore.DataStore;
import org.jcvi.jillion.core.residue.nt.NucleotideSequenceBuilder;
import org.jcvi.jillion.fasta.nt.NucleotideFastaRecord;
import org.jcvi.jillion.fasta.nt.NucleotideFastaRecordBuilder;
import org.jcvi.jillion.internal.ResourceHelper;

public  abstract class AbstractTestSequenceFastaDataStoreWithNoComment {
    static final String FASTA_FILE_PATH = "files/noComment.fasta";
    ResourceHelper RESOURCES = new ResourceHelper(AbstractTestSequenceFastaMapWithNoComment.class);
    
    NucleotideFastaRecord hrv_61 = new NucleotideFastaRecordBuilder("hrv-61",
        new NucleotideSequenceBuilder("TTAAAACTGGGTCTGGGTTGCTCCCACCCAGACCACCCATGTGGTGTTGTACACTGTTAT" +
        "TCCGGTAACTTTGTACGCCAGTTTTGAACTCCCCTACCCCTTTTGTAACTTAGAAGCTAA" +
        "ACACATCGACCAATAGCAGGCAATCACCCAGATTGCTTATGGTCAAGTACTTCTGTTTCC" +
        "CCGGTCTCCTCTGATATGCTCTACCAGGGCAAAAACAGAGTAGATCGTTATCCGCAAGAT" +
        "GCCTACGCAACGCCTAGTAACACTTTGAAGTGTTTTTGGTTGGTCGCTCAGTTACAACCC" +
        "CAGTAATAGACCTGGCAGATGAGGCTAGATATCCCCCACTGGCGACAGTGATCTAGCCTG" +
        "CGTGGCTGCCTGCACACCCTTTATGGGTGTGAAGCCAAACATATGACAAGGTGCGAAGAG" +
        "CCACGTGTGCTCATCTTGAGTCCTCCGGCCCCTGAATGCGGCTAACCTCAACCCTGCAGC" +
        "CATTGCTCACAAGCCAGTGGGTATGTGGTCGTAATGAGAAATTGCGGGACGGGACCGACT" +
        "ACTTTGGGTGTCCGTGTTTCACTTTTTTACCTTATTTTGCTTATGGTGACAATATATATA" +
        "CAGATATATATTGACACCATGGGCGCTCAGGTATCCAGACAAAACGTTGGTACTCATTCT" +
        "ACTCAGAATTCTGTTTCAAATGGTTCTAGTTTAAACTATTTTAACATTAATTACTTTAAA" +
        "GATGCGGCTTCAAGTGGAGCATCCAAATTGGAATTTTCACAAGACCCCAGCAAATTTACA" +
        "GATCCAGTCAAGGATGTTTTAGAGAAGGGAATACCAACTCTACAATCACCAACTGTTGAA" +
        "GCATGTGGTTATTCAGATAGAATCATCCAAATTACAAGAGGTGACTCCACAATTACCTCA" +
        "CAAGATGTTGCTAATGCTGTAGTTGGGTATGGAGTTTGGCCACATTACTTAACACCACAA" +
        "GATGCCACTGCTATAGATAAACCTTCTAAGCCTGACACATCTTCTAATAGATTTTACACA" +
        "TTAGAAAGCCAGACCTGGACCAATGAATCCAAGGGCTGGTGGTGGAAATTACCAGATGCT" +
        "TTGAAAGACATGGGTATTTTTGGAGAAAACATGTTTTACCATTTTCTAGGCAGAAGTGGA" +
        "TACACGGTTCATGTCCAGTGCAACGCCAGCAAGTTTCATCAGGGAACTCTTCTGGTAGCA" +
        "ATGATACCAGAGCACCAGCTAGCTACCGCTGTAGGCGGCAGTGTATCTGCAGGATACAAT" +
        "TACACACACCCTGGTGAAAAGGGTAGGGATGTTGGAAAATTAAACCGTGAATCCAATCCA" +
        "AGACAACCTAGTGATGACAATTGGTTAAATTTTGATGGCACATTATTAGGAAACTTGACA" +
        "ATATTTCCTCACCAATTCATTAACCTTAGAAGTAACAACTCGGCTACTATTATAGTACCA" +
        "TATGTTAATGCTGTCCCAATGGATTCAATGCTAAGGCACAATAATTGGAGTTTAGTCATC" +
        "ATACCCATTTGTGAGCTTAGAGGTAGCGGTGTTGATCTCACCATCCCTATTACAATTTCC" +
        "ATTAGTCCTATGTGTGCTGAATTCTCTGGAGCAAGAGCAAACAGCCAGGGGTTGCCGGTC" +
        "TTACTAACACCCGGTTCTGGCCAATTCATGACAACAGATGATTTTCAATCTCCCAGTGCT" +
        "CTACCCTGGTACCATCCTACCAAGGAAATTTCAATACCTGGACAGGTTAGAAATCTAGTG" +
        "GAATTATGCCAAGTAGATACCTTGATACCAATTAACAACACAGAAGCCAACATCAGAAAT" +
        "AAAAATATGTACACCGTACAACTTGGTGGTGAACCTGACCCTACAACCCCGGTTTTCACA" +
        "ATTAGGGTTGATATTGCATCACAACCATTAGCCACTACACTTATAGGTGAAGTTTCCAGC" +
        "TACTACACACATTGGACTGGGAGTGTTAGATTTAGTTTTATGTTCTGTGGATCAGCACTT" +
        "ACAACACTAAAGTTATTGATTGCATATACCCCACCTGGTATTAGAGTTCCAAGAAATAGA" +
        "AAAGAAGCAATGCTTGGTACACATCTAATATGGGACGTTGGTCTACAGTCCACAGTGTCA" +
        "ATGGTGGTTCCCTGGGTCAGTGCTAGTCATTATAGAAACACAACCCCAGATACATATTCA" +
        "ATAGCTGGCTTCATTACATGCTGGTATCAAACAAAACTGGTAGTTCCCCCAAACACAGCC" +
        "TCCACAGCTGATATGCTGTGCTTTGTTTCAGGGTGCAAAGATTTCTGCCTACGCATGGCA" +
        "AGAGATACTAACTTACACAAGCAAAGTGGACCTATTGAGCAAAACCCTGTGGAAAGATAT" +
        "GTAGATGAAGTTTTAAATGAAGTGCTTGTAGTCCCAAACATTAATCAGAGCAACCCTACA" +
        "ACATCCAACTCAGCACCAGTCTTAGACGCTGCTGAAACAGGTCATACCAGCAATGTTCAA" +
        "CCGGAGGACATGATTGAAACACGATATGTTCAAACCTCACAGACAAGAGATGAAATGAGT" +
        "GTAGAAAGTTTCTTGGGTAGATCAGGGTGCATACATATGTCAACATTAAATATAAACTAT" +
        "GATAACTATGATGATTCTATTGAAAACTTCAAGGTGTGGAAAATAAACCTGCAAGAGATG" +
        "GCACAAATACGTAGAAAATTTGAGTTGTTCACATATGCTAGATTTGATTCAGAGATTACA" +
        "ATTGTACCTTGTGTTGCTGGGCAAGGTGGTGACATTGGACACGTGGTCATGCAATACATG" +
        "TATGTTCCACCTGGTGCACCTACACCTGAGAAAAGAAATGATTTCACATGGCAATCAGGC" +
        "ACAAATGCATCTGTTTTCTGGCAACATGGTCAAGCTTATCCCAGATTTTCATTACCATTC" +
        "CTAAGTATTGCATCTGCATATTATATGTTTTATGATGGTTATGATGGAGATTCTGAAATA" +
        "ACGCGCTATGGAACATCAGTGACAAATGATATGGGTGCATTGTGCTTTAGAATAGTAACT" +
        "GAACAGCATACAAATCAAGTTAAAATCACAACTAGGATTTACCATAAAGCTAAACATGTT" +
        "AAAGTCTGGTGTCCTAGACCCCCCAGAGCAGTGGAATATACTAATGTGCATTTGACCAAT" +
        "TACAAGCCCAAAGATAGTGAAAAACAAGTTACCACTTTCATCAAACCTAGAGCTAACTTA" +
        "AGAGAGATTAGAACATTTGGGCCCAGTGACATGTATGTGCATGTCGGAAATTTAATATAT" +
        "AGAAATCTGCACTTATTTAATTCAGAGGCACATGATTCTGTATTAGTATCCTACTCATCA" +
        "GATTTAGTCATTTACCGCACAAACACCGTAGGTGATGACTTTATACCAACATGTGATTGC" +
        "ACACAAGCTACATATTATTGTAAGCACAAAAACAGGTACTTCCCAATCACAGTCACTAGT" +
        "CATGATTGGTACGAAATCCAAGAGAGTGAATATTATCCAAAACATATTCAATATAATCTA" +
        "TTAATTGGTGAGGGTCCTTGTGAACCAGGTGATTGTGGAGGGAAGTTACTGTGTAAACAT" +
        "GGAGTCATTGGCATTATAACTGCTGGTGGTGAAGGGCATGTTGCCTTCATAGATTTAAGA" +
        "CATTTCCTGTGTGCTGAAGAGCAAGGAGTAACAGATTATATCCACATGTTAGGTGAGGCT" +
        "TTTGGAAATGGCTTTGTAGATAGTGTTAAAGAACATGTGAATGCTATAAATCCTGTAAAT" +
        "AATATTAGTAAAAAAGTAATTAAGTGGTTGTTGAGAATTGTATCTGCTATGGTTATAATA" +
        "ATCAGAAACTCATCTGATCCCCAAACCGTTGTTGCCACTTTAACATTAATTGGATGTTCT" +
        "GGGTCACCATGGAGATTCTTAAAAGAAAAATTCTGTAAATGGACCCAACTAACTTACATT" +
        "CATAAAGAATCTGATTCTTGGCTCAAAAAATTCACCGAAATGTGCAATGCAGCAAGAGGA" +
        "CTTGAATGGATAGGGAATAAAATATCAAAATTTATAGAATGGATGAAATCAATGTTGCCA" +
        "CAAGCACAGCTTAAAGTTAAATATTTAAATGAGTTGAAAAAATTAAACCTTCTTGAAAAG" +
        "CAGATTGAGAACCTGAGAAGTGCTGATTCTAAAACTCAAGAAAGGATTAAGGTTGAGATA" +
        "GACACATTACATGATTTGTCCTGTAAATTTCTTCCACTTTATGCTAGTGAAGCCAAGAGG" +
        "ATCAAGGTGATACACAATAAATGTAATACTATCATAAAACAAAAGAAAAGGAGTGAACCG" +
        "GTTGCAGTGATGATACATGGTTCACCAGGTACTGGAAAATCCATAACAACAAATTTTCTG" +
        "GCAAGAATGATAACAAATGAGAGTGACATATATTCATTACCACCTGATCCTAAATATTTT" +
        "GATGGGTACGATCAGCAGTCTGTTGTCATAATGGATGATATCATGCAAAATCCAGATGGT" +
        "GAAGACATGGCACTATTTTGTCAGATGGTCTCTAGTGTAACTTTTATACCCCCAATGGCT" +
        "GATTTACCTGATAAAGGAAAACCCTTTGACTCCAGATTTGTTCTTTGCAGTACTAACCAC" +
        "TCCATGTTGGCCCCTCCAACAATTACATCCCTTCAGGCAATGAATAGACGCTTCTTTCTT" +
        "GATTTAGATATTGTGGTACATGATAATTACAAAGATTCACAAGGGAAACTAAATGTGTCT" +
        "AAAGCTTTTAAACCATGTGATGTTGGAACAAAAATAGGTAACGCACGTTGTTGTCCATTC" +
        "ATTTGTGGCAAGGCAGTTACATTCAAAGATCGCAACACGTGCTTGAGCTACCCATTGAGT" +
        "CAAATTTACAACCTAATTCTCCAAGAGGACAAGAGGCGTACTCATGTTGTAGATGTTATG" +
        "TCTGCTATATTTCAGGGACCAATCTCTATGGAAGTACCTCCTCCTCCTGCAATAACTGAT" +
        "TTGCTCCGATCTGTTAAGACACCTGAAGTTATTAAATATTGTGAAGACAATAAATGGACC" +
        "ATTCCAGCTGATTGTAAGATTGAGAGGGACTTAATTCTTGCTAACAACATTATTACAATT" +
        "ATAGCAAACATAATTAGCATAGCAGGTATTATCTACATTATATATAAACTATTTTGCTCA" +
        "TTTCAAGGACCATACTCTGGTGAACCCAAACCTAAAACAAAAATTCCTGAGAGGAGAGTT" +
        "GTGACACAGGGTCCTGAGGAAGAGTTTGGTCGCTCCCTGATCAAACATAACACTTGTGTG" +
        "GTGACCACTGATAATGGAAAATTTACTGGATTGGGCATTTATGACAAACTCATGATTTTA" +
        "CCCACCCATGCTGACCCTGGAAAAGAAATTTACATCAATGGGATTGCAACAAGGGTCAGT" +
        "GATTCATATGATATGTACAATAAACAAGGAATTAAACTAGAGATTACAGCTGTACTATTG" +
        "GATAGGAATGAAAAATTTAGAGACATTAGGAGATATATACCAGAGAGGGAAGATGATTAC" +
        "CCTGAGTGTAACCTAGCACTGGTAGCAAATCAGCCTGAACCAACTATCATAAGTGTGGGT" +
        "GATGTCATTTCTTACGGCAATATATTGCTTAGTGGCAACCAAACAGCACGCATGCTTAAA" +
        "TACAACTATCCCACAAAATCTGGGTACTGTGGTGGAGTCTTGTACAAAATAGGGCAAATT" +
        "ATAGGGATACATGTGGGTGGAAATGGTAGAGATGGATTTTCAGCAATGTTACTTAGGTCC" +
        "TATTTTAGTGAAACTCAGGGTGAAATCATTACATCAAAGAAAGTTCATGAATGTGGGTAT" +
        "CCAACTATACACACCCCTGCAAAAACAAAGTTACAGCCTAGTGTTTTCTTTGATGTGTTT" +
        "GAAGGTTCAAAAGAACCAGCAGTGCTCACAGAAAAGGATCCCCGTTTAACAACTGATTTT" +
        "AATCAAGCCTTATTTTCCAAATACAAAGGAAATGTTGAATGCAACATGTCTGAACACATG" +
        "AAGGTTGCCATATCACATTATTCTGCTCAATTAATGACTTTAGATATAGACCCTAGCAAT" +
        "ATAACCCTAGAGGAGAGTGTGTTTGGCACTGAAGGTTTGGAAGCTCTCGATCTAAATACT" +
        "AGTGCAGGTTTCCCATACATTAGCATGGGTATCCGAAAGAGAGATTTAATAAACAATAGT" +
        "ACAAAAGATATCACCAAGTTAAAAGTGGCCCTTGACAAGTATGGAGTTGATTTACCTATG" +
        "GTAACATTCCTTAAAGATGAACTCAGAAAGAAAGGAAAAATCATGGCTGGCAAAACAAGA" +
        "GTCATTGAAGCAAGCAGTATCAACGATACAGTTGCTTTCAGAATGACATATGGTAAACTC" +
        "TTCTCTAGTTTCCATAAAAACCCAGGGATCATCACAGGTTCAGCGGTAGGATGTGATCCC" +
        "GAAACATTTTGGTCAAAAATCCCAGTTATGCTCGATGGGGAGTGCATAATGGCATTTGAT" +
        "TACACTAATTATGATGGTAGTATACATCCCATCTGGTTTGAAGCACTCAAACAAGTTCTC" +
        "ATAAATTTATCCTTTGAGCATAGGTTAATAGACAGGTTATGTAAATCAAAACACATATTC" +
        "AAGGACACTTACTATGAAGTTGAAGGGGGGGTACCGTCAGGATGTTCTGGCACTAGTATT" +
        "TTTAATACAATGATTAACAATGTAATAATAAGAACTCTAGTCCTTGATGCATACAAATAT" +
        "ATAGATTTAGATAAGCTTAAAATAATAGCATATGGTGATGATGTCATCTTCTCTTACAAA" +
        "TACCCTCTGGATATGGAAGCAATTGCTGCAGAAGGAAACAAGTATGGTTTAACAATCACA" +
        "CCAGCTGACAAGTCTGATACCTTCAAGAAGCTTGATTACAGCAGTGTTACATTCTTGAAG" +
        "AGAGGTTTCAAACAAGATGACAAATATTCTTTTTTGATTCATCCTACTTTTCCAATTTCT" +
        "GAAATACATGAATCAATTAGGTGGACTAAGAAGCCCTCACAAATGCAGGAACACGTACTA" +
        "TCCTTGTGTCACTTAATGTGGCATAATGGCCGGGATGTGTATAAAGAATTCGAAAGGAAA" +
        "ATACGCAGTGTTAGCGCTGGACGTGCACTGTATATTCCTCCTTACGATCTCCTGTTGCAT" +
        "GAGTGGTATGAAAAATTTTAATATATAGAAATAATAAACAATTAGTTTCTTAGTTTTAT" ).build())
    .build();



protected abstract DataStore<NucleotideFastaRecord> createDataStore(File file) throws IOException;
}
